import {test,expect,type Page} from '@playwright/test';
import {section,reveal} from './navigation';
const sizes=[{width:1920,height:1080},{width:1440,height:900},{width:1366,height:768},{width:960,height:600},{width:390,height:844},{width:390,height:600}];
async function frame(page:Page){
 expect(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight&&document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 const outside=await page.locator('.content').evaluate(root=>{const edge=root.getBoundingClientRect();return [...root.querySelectorAll('button,input,select,textarea')].filter(e=>e.getClientRects().length&&!e.closest('[hidden],.calendar-grid,.account-profile-scroll,.calendar-side-scroll,.activity-list,.insight-cards')).filter(e=>{const r=e.getBoundingClientRect();return r.bottom>edge.bottom+2||r.right>edge.right+2;}).map(e=>e.getAttribute('aria-label')||e.textContent);});expect(outside).toEqual([]);
}
test('时间线卡片标记固定，长文本与来源可读，六种窗口无横向裁切',async({page,request})=>{
 test.setTimeout(60000);const tasks=await(await request.get('/api/tasks')).json(),task=tasks.tasks[0];
 const events=Array.from({length:13},(_,i)=>({kind:['user','assistant','tool','event'][i%4],timestamp:Date.now()-i*60000,text:i===2?'```sh\ngit status --short\n```\n工具结果：工作区干净。':'# 真实活动\n\n**重点**：说明当时提出的请求或执行的操作。\n\n'+'长内容与无空格文本'.repeat(500),evidence:{path:'synthetic-timeline.jsonl',line:i+1}}));
 await page.route('**/api/tasks/'+task.id+'/events',route=>route.fulfill({json:{events,nextCursor:null}}));
 for(const size of sizes){await page.setViewportSize(size);await page.goto('/history?task='+task.id);const dialog=page.getByRole('dialog');await section(page,'会话详情页面','activity');await section(page,'会话活动页面','timeline');await expect(dialog.locator('.activity-card')).toHaveCount(4);
  for(const marker of await dialog.locator('.activity-marker').all()){const box=(await marker.boundingBox())!;expect(box.width).toBeLessThan(32);expect(box.height).toBeLessThan(32);}
  await dialog.locator('.activity-toggle').first().click();const body=dialog.locator('.activity-body');await expect(body.locator('strong')).toContainText('重点');await expect(body).toBeVisible();expect(await body.evaluate(e=>e.scrollWidth<=e.clientWidth+1)).toBe(true);await dialog.getByText('来源定位',{exact:true}).click();await expect(dialog.locator('.activity-evidence')).toContainText('synthetic-timeline.jsonl');
  await dialog.getByRole('button',{name:'下一页',exact:true}).click();await expect(dialog.locator('.activity-body')).toHaveCount(0);
  const clipped=await dialog.locator('.activity-content').evaluateAll(nodes=>nodes.some(n=>{const r=n.getBoundingClientRect();return r.right>innerWidth||r.width<100;}));expect(clipped).toBe(false);await page.screenshot({path:`artifacts/screenshots/082-timeline-${size.width}-${size.height}.png`});
 }
});
test('用量范围分析填补留白，热力图无补录描边且保持原始日期值',async({page})=>{
 test.setTimeout(60000);for(const size of sizes){await page.setViewportSize(size);await page.goto('/usage?demo=1');await expect(page.locator('.heatmap-panel')).toBeVisible();await frame(page);await expect(page.locator('.heatmap-cell.estimated-day')).toHaveCount(0);expect(await page.locator('.heatmap-grid button').first().evaluate(e=>getComputedStyle(e).boxShadow)).toBe('none');await page.locator('.heatmap-grid button').first().hover();await expect(page.locator('.heatmap-readout')).toContainText('日志实测');if(!await page.locator('.usage-insights:visible').count())await section(page,'用量页面','analysis');await page.locator('.insight-heading:visible').getByRole('button',{name:'费用覆盖'}).click();await expect(page.locator('.insight-cards:visible article[data-active=true]')).toContainText('未知模型不猜价');await page.screenshot({path:`artifacts/screenshots/082-usage-${size.width}-${size.height}.png`});}
});
test('日历推荐采纳前不保存，所选日期正确，保存后呈现实体日程',async({page,request})=>{
 test.setTimeout(60000);for(const size of sizes){await page.setViewportSize(size);await page.goto('/calendar');await page.getByLabel('日历日期').fill('2026-10-09');await expect(page.locator('.calendar-side')).toContainText('2026-10-09');await expect(page.locator('.calendar-recommendation')).toHaveCount(4);await frame(page);for(const cell of await page.locator('.calendar-day').all()){const box=(await cell.boundingBox())!;expect(box.height).toBeGreaterThanOrEqual(30);}await page.screenshot({path:`artifacts/screenshots/082-calendar-${size.width}-${size.height}.png`});}
 const before=await(await request.get('/api/schedules')).json();await page.getByLabel('采纳：每日计划').click();await expect(await reveal(page,page.getByLabel('日程标题'))).toHaveValue('每日计划');await expect(await reveal(page,page.getByLabel('日程开始'))).toHaveValue('2026-10-09T09:00');expect((await(await request.get('/api/schedules')).json()).length).toBe(before.length);
 await (await reveal(page,page.getByLabel('日程标题'))).fill('推荐采纳验收');await (await reveal(page,page.getByRole('button',{name:'保存日程',exact:true}))).click();await expect(page.locator('.calendar-saved').filter({hasText:'推荐采纳验收'})).toBeVisible();await page.reload();await expect(page.locator('.calendar-saved').filter({hasText:'推荐采纳验收'})).toBeVisible();const saved=(await(await request.get('/api/schedules')).json()).find((s:{title:string})=>s.title==='推荐采纳验收');await request.delete('/api/schedules/'+saved.id);
});
test('账号资料保存重载、兼容局部更新，头像圆形居中且操作始终可达',async({page,request})=>{
 test.setTimeout(60000);const old=(await(await request.get('/api/auth/status')).json()).user;
 await page.goto('/account');await page.getByLabel('电话',{exact:true}).fill('+86 138-0000-0000');await page.getByLabel('邮箱',{exact:true}).fill('profile-test@example.com');await page.getByLabel('性别',{exact:true}).selectOption('private');await page.getByLabel('生日',{exact:true}).fill('2000-02-29');await page.getByLabel('个人签名',{exact:true}).fill('真实资料，选择自己的工作节奏。');await page.getByRole('button',{name:'保存资料',exact:true}).click();await expect(page.getByRole('status')).toContainText('个人资料已保存');await page.reload();await expect(page.getByLabel('邮箱',{exact:true})).toHaveValue('profile-test@example.com');
 for(const size of sizes){await page.setViewportSize(size);await frame(page);const avatar=page.getByLabel('打开账号中心');const box=(await avatar.boundingBox())!;expect(Math.abs(box.width-box.height)).toBeLessThan(.5);expect(await avatar.evaluate(e=>getComputedStyle(e).padding)).toBe('0px');await page.screenshot({path:`artifacts/screenshots/082-account-${size.width}-${size.height}.png`});}
 const invalid=await request.patch('/api/account/profile',{data:{displayName:old.displayName,birthday:'2001-02-29'}});expect(invalid.ok()).toBe(false);expect((await(await request.get('/api/auth/status')).json()).user.birthday).toBe('2000-02-29');
 await request.patch('/api/account/profile',{data:{displayName:old.displayName,phone:old.phone||'',email:old.email||'',gender:old.gender||'',birthday:old.birthday||'',signature:old.signature||''}});
});

test('官方默认单价无需保存即可计价，自定义覆盖后删除可恢复默认',async({page,request})=>{
 const timestamp=Date.now(),query=`start=${timestamp-86400000}&end=${timestamp+86400000}&provider=codex&model=gpt-6.1-sol`,input={id:'pricing-082-sample',provider:'codex',model:'gpt-6.1-sol',input:1000000,output:100000,timestamp,note:'合成计价验收',version:0,refine:false};
 expect((await request.post('/api/usage/manual',{data:input})).ok()).toBe(true);
 const initial=await(await request.get('/api/usage?'+query)).json();expect(initial.costs[0].amount).toBe(3);expect(initial.costs[0].default).toBe(true);
 await page.goto('/usage?filter-usage-model=gpt-6.1-sol');await section(page,'用量页面','prices');await section(page,'价格页面','contract');await expect(page.getByRole('button',{name:'修改：gpt-6.1-sol',exact:true})).toBeVisible();await page.getByRole('button',{name:'修改：gpt-6.1-sol',exact:true}).click();await expect(await reveal(page,page.getByLabel('单价模型'))).toHaveValue('gpt-6.1-sol');await expect(await reveal(page,page.getByLabel('input 单价',{exact:true}))).toHaveValue('2');await expect(await reveal(page,page.getByLabel('cacheRead 单价',{exact:true}))).toHaveValue('0.1');
 const saved=await request.post('/api/usage/prices',{data:{provider:'codex',model:'gpt-6.1-sol',currency:'CNY',date:'2020-01-01',input:6,output:20,cacheRead:.1,cacheWrite:6,cacheWriteLong:6}});expect(saved.ok()).toBe(true);const price=await saved.json();const overridden=await(await request.get('/api/usage?'+query)).json();expect(overridden.costs[0].amount).toBe(8);expect(overridden.costs[0].default).toBe(false);expect(overridden.costs[0].currency).toBe('CNY');
 await request.delete('/api/usage/prices/'+price.id);expect((await(await request.get('/api/usage?'+query)).json()).costs[0].amount).toBe(3);await request.delete('/api/usage/manual',{data:{id:input.id,version:1}});
});
