import {test,expect} from '@playwright/test';
test('未配置数据库仍可访问设置、演示和模型占位',{tag:'@settings'},async({page})=>{await page.goto('http://127.0.0.1:4319/');await expect(page.getByRole('heading',{name:'配置数据库',exact:true})).toBeVisible();await expect(page.getByLabel('数据库密码')).toHaveValue('');await expect(page.getByLabel('DeepSeek API Key')).toHaveCount(0);await expect(page.getByLabel('数据库主机')).toHaveValue('');await page.getByRole('button',{name:'查看演示体验'}).click();await page.getByRole('button',{name:'报告中心',exact:true}).click();await page.getByRole('button',{name:'生成本地事实'}).click();await expect(page.getByRole('heading',{name:/演示日报/})).toBeVisible();});
test('日报补充、日程、上下文预览与模拟模型流',async({page,request})=>{
 await page.goto('/');await page.getByRole('button',{name:'报告中心',exact:true}).click();await page.getByRole('button',{name:'生成本地事实'}).click();await page.getByLabel('报告补充').fill('用户补充：下次验证索引');await page.getByRole('button',{name:'保存报告补充'}).click();await expect(page.getByRole('status')).toContainText('报告补充已保存');await page.getByRole('button',{name:'加入助手上下文'}).click();await page.getByRole('button',{name:'内置助手',exact:true}).click();await expect(page.locator('.context-preview')).toContainText('用户补充：下次验证索引');await page.getByRole('button',{name:'确认内容并发送'}).click();await expect(page.getByText(/先验证任务完成状态/).first()).toBeVisible();await expect(page.getByRole('button',{name:'确认内容并发送'})).toBeEnabled();
 const chats=await(await request.get('/api/assistant/chats')).json();expect(chats[0].messages[1].status).toBe('complete');expect(JSON.stringify(chats)).not.toContain('synthetic-e2e-key');expect(chats[0].messages[1].sources[0].type).toBe('report');
 await page.getByRole('button',{name:'日历日程',exact:true}).click();await page.getByRole('button',{name:'新建日程'}).click();await page.getByLabel('日程标题').fill('集成验收日程');await page.getByRole('button',{name:'保存日程'}).click();await expect(page.getByRole('button',{name:/集成验收日程/}).first()).toBeVisible();await page.screenshot({path:'artifacts/screenshots/calendar-1440.png',fullPage:true,animations:'disabled'});await page.reload();await page.getByRole('button',{name:'日历日程',exact:true}).click();await expect(page.getByRole('button',{name:/集成验收日程/}).first()).toBeVisible();
 const settings=await(await request.get('/api/settings')).json();expect(settings.database.password).toBeUndefined();expect(settings.key).toBeUndefined();expect(settings.hasKey).toBe(true);
});
test('模型停止与上下文约束',async({request})=>{const tasks=await(await request.get('/api/tasks')).json();const preview=await(await request.post('/api/assistant/context',{data:{refs:[{type:'task',id:tasks.tasks[0].id}]}})).json();expect(preview.text).not.toContain('正文：');const bad=await request.post('/api/assistant/context',{data:{refs:[{type:'task',id:'C:\\private.txt'}]}});expect(bad.status()).toBe(400);const changed=await request.post('/api/assistant/generate',{data:{previewId:preview.id,fingerprint:'wrong',question:'分析'}});expect(changed.status()).toBe(400);});
test('助手停止、AI 版本保存、日程草稿和引用返回',async({page,request})=>{
 const tasks=await(await request.get('/api/tasks')).json();await page.goto('/');await page.getByRole('button',{name:'内置助手',exact:true}).click();await page.getByLabel('搜索上下文').fill(tasks.tasks[0].title);await page.locator('.context-row').filter({hasText:tasks.tasks[0].title}).first().getByRole('checkbox').first().check();await page.getByRole('button',{name:'预览实际发送内容'}).click();await page.getByLabel('助手问题').fill('慢速验证：分析当前进展');await page.getByRole('button',{name:'确认内容并发送'}).click();await expect(page.getByText(/根据所选事实/).first()).toBeVisible();await page.getByRole('button',{name:'停止生成'}).click();await expect(page.getByRole('button',{name:'确认内容并发送'})).toBeEnabled();await expect.poll(async()=>{const chats=await(await request.get('/api/assistant/chats')).json();return chats.find((c:{title:string})=>c.title.includes('慢速验证'))?.messages.at(-1).status;}).toBe('interrupted');
 await page.getByLabel('助手问题').fill('分析当前任务');await page.getByRole('button',{name:'确认内容并发送'}).click();await expect(page.getByRole('button',{name:'确认内容并发送'})).toBeEnabled();const report=await(await request.post('/api/reports',{data:{date:new Date(Date.now()+28800000).toISOString().slice(0,10)}})).json();const chats=await(await request.get('/api/assistant/chats')).json();const saved=await(await request.post(`/api/reports/${report.id}/analysis`,{data:{chatId:chats[0].id}})).json();expect(saved.versions.at(-1).model).toBe('deepseek-flash');
 await page.getByRole('button',{name:'创建日程草稿，编辑后确认'}).click();await expect(page.getByLabel('日程标题')).toHaveValue('AI 分析跟进（待编辑）');await expect(page.getByRole('button',{name:'保存日程'})).toBeVisible();const schedules=await(await request.get('/api/schedules')).json();expect(schedules.some((s:{title:string})=>s.title==='AI 分析跟进（待编辑）')).toBe(false);
});
test('模拟到期通知处理入库且不重复，新增页面适配窄窗口',async({page,request,context})=>{
 await page.addInitScript(()=>{localStorage.setItem('agentdock-notifications','true');Object.defineProperty(window,'Notification',{configurable:true,value:class {static permission='granted';static requestPermission=async()=> 'granted';constructor(){sessionStorage.setItem('notification-count',String(Number(sessionStorage.getItem('notification-count')||0)+1));}}});});const schedule=await(await request.post('/api/schedules',{data:{title:'到期提醒验收',start:Date.now()-60000,end:Date.now()+3600000,reminderMinutes:0}})).json();await page.goto('/');await expect.poll(async()=>{const schedules=await(await request.get('/api/schedules')).json();return schedules.find((s:{id:string})=>s.id===schedule.id).notifiedAt;}).toBeTruthy();expect(await page.evaluate(()=>sessionStorage.getItem('notification-count'))).toBe('1');await page.reload();await page.waitForTimeout(500);expect(await page.evaluate(()=>sessionStorage.getItem('notification-count'))).toBe('1');
 for(const view of ['报告中心','日历日程','内置助手','设置']){await page.getByRole('button',{name:view,exact:true}).click();await page.screenshot({path:`artifacts/screenshots/module-${view}-1440.png`,fullPage:true,animations:'disabled'});}
 await page.setViewportSize({width:390,height:844});for(const view of ['报告中心','日历日程','内置助手','设置']){await page.getByLabel('打开导航').click();await page.getByRole('button',{name:view,exact:true}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await expect.poll(()=>page.locator('.sidebar').evaluate(el=>el.getBoundingClientRect().right)).toBeLessThanOrEqual(0);await page.screenshot({path:`artifacts/screenshots/module-${view}-mobile.png`,fullPage:true,animations:'disabled'});}
});
test('同一聊天并发生成被拒绝，避免覆盖上下文与历史',async({request})=>{const list=await(await request.get('/api/tasks')).json();const preview=await(await request.post('/api/assistant/context',{data:{refs:[{type:'task',id:list.tasks[0].id}]}})).json();const chats=await(await request.get('/api/assistant/chats')).json();const chat=chats[0];const data={previewId:preview.id,fingerprint:preview.fingerprint,chatId:chat.id,question:'慢速验证：并发生成测试'};const first=request.post('/api/assistant/generate',{data});await expect.poll(async()=>{const c=await(await request.get(`/api/assistant/chats/${chat.id}`)).json();return c.messages.at(-1).text;}).toBe(data.question);const second=await request.post('/api/assistant/generate',{data});expect(second.status()).toBe(400);expect((await second.json()).error).toContain('正在生成');expect((await first).status()).toBe(200);});
test('连接测试保留未保存配置，保存后才清空凭据',async({page})=>{await page.route('**/api/settings',async route=>{const response=await route.fetch();const data=await response.json();await route.fulfill({json:{...data,databaseFromEnv:false,keyFromEnv:false}});});await page.goto('/settings');await page.getByLabel('数据库主机').fill('db.synthetic.example');await page.getByLabel('数据库用户名').fill('synthetic-user');await page.getByLabel('数据库名',{exact:true}).fill('synthetic_db');await page.getByLabel('数据库密码').fill('synthetic-password');await page.route('**/api/settings/database/test',route=>route.fulfill({json:{ok:true,version:'8.4.0'}}));await page.getByRole('button',{name:'测试连接',exact:true}).click();await expect(page.getByRole('status')).toContainText('连接测试通过');await expect(page.getByLabel('数据库密码')).toHaveValue('synthetic-password');await expect(page.getByLabel('数据库主机')).toHaveValue('db.synthetic.example');await page.getByLabel('DeepSeek API Key').fill('synthetic-unsaved-key');await page.route('**/api/settings/model/test',route=>route.fulfill({json:{models:['deepseek-flash','synthetic-model']}}));await page.getByRole('button',{name:'测试模型连接'}).click();await expect(page.getByLabel('DeepSeek API Key')).toHaveValue('synthetic-unsaved-key');await expect(page.locator('#deepseek-models option')).toHaveCount(2);await page.route('**/api/settings/model',route=>route.fulfill({json:{hasKey:true}}));await page.getByRole('button',{name:'保存模型设置'}).click();await expect(page.getByLabel('DeepSeek API Key')).toHaveValue('');await expect(page.getByRole('status')).toContainText('模型设置已保存');await page.unrouteAll({behavior:'wait'});});
