import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,mkdirSync,writeFileSync,appendFileSync } from 'node:fs';
import { DatabaseSync } from 'node:sqlite';
import path from 'node:path';
import { emptyTask,finalize } from '../server/parsers.mjs';
import { readLog } from '../server/collector.mjs';
import { openStore,canInitialize } from '../server/store.mjs';
import { generateReport,migrateLegacy,buildContext } from '../server/workspace.mjs';
import { testStore } from './mysql-helper.mjs';
import {createOwner,login,authStatus,account} from '../server/auth.mjs';
import {saveUsage,usageOverview,usageRecords,validatePrice} from '../server/usage.mjs';
const enabled=process.env.AGENTDOCK_INTEGRATION==='true';
test('MySQL: 账号初始化竞态、会话吊销和修改密码不泄露哈希',{skip:!enabled},async()=>{
 const {store,config}=await testStore('agentdock_test_auth');try{
 assert.equal(await canInitialize(config),true);
 const owner={username:'synthetic_owner',password:'synthetic-owner-pass'};const results=await Promise.allSettled([createOwner(store,owner),createOwner(store,owner)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(await canInitialize(config),false);
 const a=await login(store,owner),b=await login(store,{...owner,desktop:true,remember:true});assert.equal((await authStatus(store,a.token)).user.username,owner.username);assert.equal(a.user.password_hash,undefined);assert.ok(!(await store.rows('SELECT password_hash FROM ad_users'))[0].password_hash.includes(owner.password));await assert.rejects(login(store,{...owner,password:'wrong-password'}));
 const sessions=await account(store,{token:a.token,action:'sessions'});assert.equal(sessions.length,2);assert.ok(sessions.some(s=>s.current));assert.ok(sessions.every(s=>!s.id.includes(a.token)));
 await account(store,{token:a.token,action:'revoke'});assert.equal((await authStatus(store,b.token)).user,null);await account(store,{token:a.token,action:'profile',displayName:'中文所有者'});assert.equal((await authStatus(store,a.token)).user.displayName,'中文所有者');
 await account(store,{token:a.token,action:'password',currentPassword:owner.password,password:'synthetic-new-password'});assert.equal((await authStatus(store,a.token)).user,null);await assert.rejects(login(store,owner));const c=await login(store,{...owner,password:'synthetic-new-password'});await account(store,{token:c.token,action:'logout'});assert.equal((await authStatus(store,c.token)).user,null);
 }finally{await store.close();}
});
test('MySQL: 请求分段取最大值、累计双记录去重、历史单价与币种分开',{skip:!enabled},async()=>{
 const {store}=await testStore('agentdock_test_usage');try{
 const timestamp=Date.parse('2026-09-30T12:00:00+08:00'),task=finalize(emptyTask('claude','synthetic-usage','synthetic.jsonl',{updatedAt:timestamp,createdAt:timestamp,title:'用量验收'}));
 const u={id:'a'.repeat(64),model:'synthetic',timestamp,input:100,cacheRead:60,cacheWrite:10,output:5,total:105,cacheWriteLong:0,mode:'request',evidence:{path:'synthetic.jsonl',line:1}};
 task._newUsage=[u,{...u,output:20,total:120}];await store.upsert(task);await store.upsert({...task,_newUsage:[u]});assert.equal(Number((await store.rows('SELECT COUNT(*) n FROM ad_usage'))[0].n),1);
 const record=(await usageRecords(store,{start:timestamp-86400000,end:timestamp+86400000})).records[0];assert.equal(record.output,20);assert.equal(record.total,120);
 const price={provider:'claude',model:'synthetic',currency:'USD',date:'2026-09-01',input:2,output:4,cacheRead:1,cacheWrite:3,cacheWriteLong:6};await store.putDocument('price',validatePrice(price));await store.putDocument('price',validatePrice({...price,date:'2026-09-30',currency:'CNY',input:10,output:20,cacheRead:5,cacheWrite:15,cacheWriteLong:30}));
 let overview=await usageOverview(store,{start:timestamp-86400000,end:timestamp+86400000});assert.equal(overview.summary.total,120);assert.equal(overview.coverage.measuredSessions,1);assert.equal(overview.costs.reduce((s,c)=>s+c.records,0),1);assert.equal(overview.costs.find(c=>c.currency==='CNY').amount,.00115);
 const codex={...task,id:'codex-synthetic',provider:'codex',_newUsage:[{...u,id:'b'.repeat(64),mode:'codex_direct'}]};await saveUsage(store,codex);await saveUsage(store,{...codex,_codexHasTotals:true,_newUsage:[{...u,id:'c'.repeat(64),mode:'codex_cumulative'}]});assert.equal(Number((await store.rows('SELECT COUNT(*) n FROM ad_usage WHERE task_id=?',[codex.id]))[0].n),1);
 const snapshot=(id,input,output,time)=>({...u,id:id.repeat(64),input,output,total:input+output,cacheRead:0,cacheWrite:0,timestamp:time,mode:'codex_cumulative',cumulative:{input_tokens:input,cached_input_tokens:0,cache_write_input_tokens:0,output_tokens:output,total_tokens:input+output}});const merged={...task,id:'codex-archive-merge',provider:'codex',_codexHasTotals:true,_newUsage:[snapshot('f',200,20,timestamp+10)]};await saveUsage(store,merged);await saveUsage(store,{...merged,_newUsage:[snapshot('9',100,10,timestamp)]});assert.equal(Number((await store.rows('SELECT SUM(total_tokens) total FROM ad_usage WHERE task_id=?',[merged.id]))[0].total),220);await saveUsage(store,merged);assert.equal(Number((await store.rows('SELECT SUM(total_tokens) total FROM ad_usage WHERE task_id=?',[merged.id]))[0].total),220);
 const missing={...task,_newUsage:[{...u,id:'d'.repeat(64),input:null,total:null,output:3,model:'missing-model'}]};await saveUsage(store,missing);await saveUsage(store,missing);overview=await usageOverview(store,{start:timestamp-86400000,end:timestamp+86400000});assert.equal(overview.summary.incomplete,1);assert.equal((await usageRecords(store,{start:timestamp-86400000,end:timestamp+86400000})).records.find(r=>r.model==='missing-model').input,null);
 await assert.rejects(store.transaction(async tx=>{await saveUsage(tx,{...task,_newUsage:[{...u,id:'e'.repeat(64)}]});throw new Error('事务中断');}));assert.equal(Number((await store.rows('SELECT COUNT(*) n FROM ad_usage WHERE id=?',['e'.repeat(64)]))[0].n),0);
 }finally{await store.close();}
});
test('MySQL: 原子断点、回滚、中文查询、确认时间与重启', {skip:!enabled}, async()=>{
 const {store,config}=await testStore('agentdock_test_store');const t=finalize(emptyTask('codex','test-id','sample.jsonl',{title:'修复同步😀',summary:'来源摘要',updatedAt:Date.now()}));
 try {
 const event={kind:'assistant',timestamp:Date.now(),text:'同一轮回复',evidence:{path:'desktop.jsonl',line:1}};t._newEvents=[event];await store.upsert(t);await store.upsert({...t,_newEvents:[{...event,evidence:{path:'archive.jsonl',line:5}}]});assert.equal((await store.events({task:t.id})).length,1);await store.upsert(t);assert.equal((await store.list()).total,1);
 await assert.rejects(store.transaction(async tx=>{await tx.saveCheckpoint('sample.jsonl',{size:20,mtimeMs:1},20,2,t);await tx.patch(t.id,{note:'回滚的备注'});throw new Error('模拟中断');}));assert.equal(await store.checkpoint('sample.jsonl'),null);assert.equal((await store.get(t.id)).annotation.note,'');
 await store.transaction(async tx=>{await tx.upsert(t);await tx.saveCheckpoint('sample.jsonl',{size:20,mtimeMs:1},20,2,t);});assert.equal((await store.checkpoint('sample.jsonl')).line,2);
 await store.patch(t.id,{note:'人工验证',manualStatus:'done',goalGroup:'交付首版',summaryOverride:'人工补充'});const confirmed=(await store.get(t.id)).annotation.confirmedAt;await store.patch(t.id,{note:'更新备注'});assert.equal((await store.get(t.id)).annotation.confirmedAt,confirmed);await store.upsert({...t,summary:'新的来源回复'});assert.equal((await store.list({q:'首版'})).total,1);assert.match(await store.export(t.id),/人工补充/);
 await store.close();const reopened=await openStore(config);assert.equal((await reopened.get(t.id)).annotation.note,'更新备注');await reopened.close();
 }finally{await store.close().catch(()=>{});}
});
test('MySQL: 跨日完整活动、报告补充与上下文、重复迁移', {skip:!enabled},async()=>{
 const {store}=await testStore('agentdock_test_reports');mkdirSync('artifacts/unit',{recursive:true});const dir=mkdtempSync(path.resolve('artifacts/unit/migration-'));const file=path.join(dir,'old.sqlite');
 try{
 const at=Date.parse('2026-09-30T12:00:00+08:00');const t=finalize(emptyTask('claude','period-id','period.jsonl',{title:'跨日记录',createdAt:at,updatedAt:at+86400000,summary:'次日总结'}));t._newEvents=Array.from({length:230},(_,i)=>({kind:'assistant',timestamp:at+i,text:'本期进展 '+i,evidence:{path:'period.jsonl',line:i+1}}));t._newEvents.push({kind:'assistant',timestamp:at+86400000,text:'次日总结',evidence:{path:'period.jsonl',line:300}});await store.upsert(t);
 const r=await generateReport(store,{date:'2026-09-30'});assert.equal(r.facts.activityCount,230);assert.match(r.facts.items[0].summary,/229/);assert.doesNotMatch(r.facts.items[0].summary,/次日/);await store.putDocument('report',{...r,userText:'人工补充',versions:[{text:'AI 分析',model:'mock'}]});assert.equal((await generateReport(store,{date:'2026-09-30'})).userText,'人工补充');
 const preview=await buildContext(store,[{type:'task',id:t.id}]);assert.match(preview.text,/跨日记录/);assert.ok(preview.id);await assert.rejects(buildContext(store,[{type:'task',id:'C:\\private.txt'}]));
 const old=new DatabaseSync(file);old.exec('CREATE TABLE tasks(id TEXT,record TEXT);CREATE TABLE annotations(task_id TEXT,value TEXT,updated_at INTEGER);CREATE TABLE checkpoints(path TEXT,size INTEGER,mtime INTEGER,offset INTEGER,line INTEGER,state TEXT)');old.prepare('INSERT INTO tasks VALUES(?,?)').run(t.id,JSON.stringify(t));old.prepare('INSERT INTO annotations VALUES(?,?,?)').run(t.id,JSON.stringify({note:'旧备注',confirmedAt:at,manualStatus:'done'}),at);old.close();await migrateLegacy(store,file);assert.equal((await store.get(t.id)).annotation.confirmedAt,at);await store.patch(t.id,{note:'目标库编辑'});await migrateLegacy(store,file);assert.equal((await store.get(t.id)).annotation.note,'目标库编辑');assert.equal((await store.list()).total,1);
 }finally{await store.close();}
});
import { testDatabase,databaseError,connectionOptions } from '../server/store.mjs';
import mysql from 'mysql2/promise';
import {randomUUID} from 'node:crypto';
test('MySQL: 只读测试、数据库缺失、连接失败、TLS 与权限不足',{skip:!enabled},async()=>{
 const {store,config}=await testStore('agentdock_test_health');
 const connection=await mysql.createConnection(connectionOptions(config));const username='agentdock_test_'+randomUUID().replaceAll('-','').slice(0,16);
 try {
 const before=await store.rows('SELECT table_name FROM information_schema.tables WHERE table_schema=?',[config.database]);await testDatabase(config);const after=await store.rows('SELECT table_name FROM information_schema.tables WHERE table_schema=?',[config.database]);assert.deepEqual(before,after);
 await assert.rejects(testDatabase({...config,database:'agentdock_test_missing_'+randomUUID().slice(0,8)}),/数据库不存在/);
 await assert.rejects(testDatabase({...config,port:1}),/无法连接|超时/);
 await assert.rejects(testDatabase({...config,tls:true,ca:'invalid synthetic certificate'}),/证书|数据库操作失败/);
 await connection.query(`CREATE USER '${username}'@'%' IDENTIFIED BY 'synthetic-readonly-only'`);await connection.query(`GRANT SELECT ON \`${config.database}\`.* TO '${username}'@'%'`);
 assert.equal((await testDatabase({...config,user:username,password:'synthetic-readonly-only'})).ok,true);await assert.rejects(openStore({...config,user:username,password:'synthetic-readonly-only'},true),/权限/);
 const id=(await connection.query('SELECT CONNECTION_ID() id'))[0][0].id;const killer=await mysql.createConnection(connectionOptions(config));await killer.query('KILL '+Number(id));await killer.end();await assert.rejects(connection.query('SELECT 1'));assert.equal((await store.rows('SELECT 1 n'))[0].n,1);
 assert.match(databaseError({code:'ER_ACCESS_DENIED_ERROR'}),/认证失败/);
 }finally {const cleanup=await mysql.createConnection(connectionOptions(config));await cleanup.query(`DROP USER IF EXISTS '${username}'@'%'`);await cleanup.end();await connection.end().catch(()=>{});await store.close();}
});
test('MySQL: 迁移中断重跑不修改源文件、不覆盖用户编辑',{skip:!enabled},async()=>{
 const {store}=await testStore('agentdock_test_resume');const dir=mkdtempSync(path.resolve('artifacts/unit/migration-'));const file=path.join(dir,'old.sqlite');const source=new DatabaseSync(file);source.exec('CREATE TABLE tasks(id TEXT,record TEXT);CREATE TABLE annotations(task_id TEXT,value TEXT,updated_at INTEGER);CREATE TABLE checkpoints(path TEXT,size INTEGER,mtime INTEGER,offset INTEGER,line INTEGER,state TEXT)');for(let i=0;i<3;i++){const t=finalize(emptyTask('pi','migration-'+i,'source.jsonl',{title:'迁移会话 '+i}));source.prepare('INSERT INTO tasks VALUES(?,?)').run(t.id,JSON.stringify(t));}source.close();const {readFileSync}=await import('node:fs');const original=readFileSync(file);let count=0;const wrapper=Object.create(store);wrapper.transaction=fn=>{if(++count===2)throw new Error('模拟迁移中断');return store.transaction(fn);};
 try{await assert.rejects(migrateLegacy(wrapper,file),/中断/);assert.equal((await store.list()).total,1);await migrateLegacy(store,file);await migrateLegacy(store,file);assert.equal((await store.list()).total,3);assert.deepEqual(readFileSync(file),original);}finally{await store.close();}
});
import {Collector} from '../server/collector.mjs';
test('MySQL: Cursor 独立消息完整导入、重复采集与用户标记保留',{skip:!enabled},async()=>{
 const {store}=await testStore('agentdock_test_cursor');const dir=mkdtempSync(path.resolve('artifacts/unit/cursor-'));const root=path.join(dir,'Cursor');mkdirSync(path.join(root,'globalStorage'),{recursive:true});const file=path.join(root,'globalStorage','state.vscdb');const db=new DatabaseSync(file);db.exec('CREATE TABLE composerHeaders(composerId TEXT,value TEXT);CREATE TABLE cursorDiskKV(key TEXT,value TEXT)');const start=Date.parse('2026-09-29T08:00:00Z');const headers=Array.from({length:220},(_,i)=>({bubbleId:'bubble-'+i,type:i%2?2:1,createdAt:new Date(start+i*60000).toISOString()}));db.prepare('INSERT INTO composerHeaders VALUES(?,?)').run('history-id',JSON.stringify({composerId:'history-id',createdAt:start,isArchived:true}));const insert=db.prepare('INSERT INTO cursorDiskKV VALUES(?,?)');insert.run('composerData:history-id',JSON.stringify({composerId:'history-id',createdAt:start,fullConversationHeadersOnly:headers,conversationMap:{},workspaceIdentifier:{uri:{fsPath:dir}}}));db.exec('BEGIN');for(const h of headers)insert.run('bubbleId:history-id:'+h.bubbleId,JSON.stringify({...h,text:'历史消息 '+h.bubbleId}));db.exec('COMMIT');db.close();const collector=new Collector(store,{home:dir,codex:dir,claude:dir,cursor:root},()=>{});
 try{await collector.cursorIndex();const t=(await store.list({provider:'cursor'})).tasks[0];assert.equal(t.partial,false);assert.equal(t.archived,true);assert.equal(t.cwd,dir);assert.equal(t.summary,'历史消息 bubble-219');assert.equal((await store.events({task:t.id,start,end:start+86400000})).length,220);const annotation=(await store.patch(t.id,{note:'保留的用户备注',manualStatus:'done'})).annotation;await collector.cursorIndex();assert.equal((await store.list({provider:'cursor'})).total,1);assert.equal((await store.events({task:t.id,start,end:start+86400000})).length,220);assert.deepEqual((await store.get(t.id)).annotation,annotation);assert.match((await store.get(t.id)).summaryEvidence.locator,/bubbleId=bubble-219/);}finally{await collector.stop();await store.close();}
});
test('MySQL: 未变化日志只读断点头信息，追加后才加载完整状态',{skip:!enabled},async()=>{const {store}=await testStore('agentdock_test_headers');const dir=mkdtempSync(path.resolve('artifacts/unit/headers-'));const codex=path.join(dir,'.codex');mkdirSync(path.join(codex,'sessions'),{recursive:true});const file=path.join(codex,'sessions','sample.jsonl');const timestamp=new Date().toISOString();const line=(role,text)=>({type:'response_item',timestamp,payload:{type:'message',role,channel:role==='assistant'?'final':undefined,content:[{type:'text',text}]}});writeFileSync(file,[{type:'session_meta',timestamp,payload:{id:'headers-id',cwd:dir,source:'cli'}},line('user','实现断点头信息检查'),line('assistant','首次采集完成')].map(JSON.stringify).join('\n')+'\n');const collector=new Collector(store,{home:dir,codex,claude:path.join(dir,'.claude'),cursor:path.join(dir,'cursor')},()=>{});let loads=0;const checkpoint=store.checkpoint.bind(store);store.checkpoint=async file=>{loads++;return checkpoint(file);};try{await collector.scan();assert.equal(loads,1);await collector.scan();assert.equal(loads,1);appendFileSync(file,JSON.stringify(line('assistant','追加采集完成'))+'\n');await collector.scan();assert.equal(loads,2);assert.equal((await store.list()).tasks[0].summary,'追加采集完成');}finally{await collector.stop();await store.close();}});
import {goalPut,goalGet,goalLink,migrateGoalGroups} from '../server/goals.mjs';
test('MySQL: 工作目标、旧文本迁移、完整分页与待处理口径',{skip:!enabled},async()=>{
 const {store,config}=await testStore('agentdock_test_goals');const dir=mkdtempSync(path.resolve('artifacts/unit/goals-'));mkdirSync(path.join(dir,'.git'));mkdirSync(path.join(dir,'other','.git'),{recursive:true});const now=Date.now();const a=finalize(emptyTask('codex','goal-a','sample.jsonl',{cwd:dir,title:'目标会话 A',createdAt:now,updatedAt:now})),b=finalize(emptyTask('claude','goal-b','sample.jsonl',{cwd:dir,title:'目标会话 B',createdAt:now,updatedAt:now})),other=finalize(emptyTask('pi','goal-c','sample.jsonl',{cwd:path.join(dir,'other'),createdAt:now,updatedAt:now}));a._newEvents=Array.from({length:220},(_,i)=>({timestamp:now,kind:i%2?'assistant':'user',text:'分页记录 '+i,evidence:{path:'sample.jsonl',line:i+1}}));
 try{await store.upsert(a);await store.upsert(b);await store.upsert(other);assert.equal((await store.overview([],{})).needsAttention,0);assert.equal((await store.overview([],{})).today,1);await store.patch(a.id,{needsReview:true,goalGroup:'同一交付',note:'迁移保留备注'});await store.patch(b.id,{goalGroup:'同一交付'});assert.equal((await store.overview([],{})).needsAttention,1);await migrateGoalGroups(store);await migrateGoalGroups(store);const migrated=await store.rows('SELECT id FROM ad_goals');assert.equal(migrated.length,1);let g=await goalGet(store,migrated[0].id);assert.equal(g.sessions.length,2);assert.equal(g.needsReview,true);g=await goalPut(store,{id:g.id,title:g.title,status:'done',note:'用户目标备注'});const confirmed=g.confirmedAt;await migrateGoalGroups(store);assert.equal((await goalGet(store,g.id)).note,'用户目标备注');assert.equal((await goalGet(store,g.id)).confirmedAt,confirmed);await assert.rejects(goalLink(store,{id:g.id,taskId:other.id}),/同项目/);await goalLink(store,{id:g.id,taskId:b.id,remove:true});assert.equal((await goalGet(store,g.id)).sessions.length,1);assert.equal((await store.get(a.id)).annotation.note,'迁移保留备注');const preview=await buildContext(store,[{type:'goal',id:g.id}]);assert.ok(preview.text.includes('用户目标备注'));let cursor,events=[];do{const page=await store.timeline({id:a.id,cursor});events.push(...page.events);cursor=page.nextCursor;}while(cursor);assert.equal(events.length,220);assert.equal(new Set(events.map(e=>e.text)).size,220);assert.equal((await store.timeline({goalId:g.id})).events.length,50);await store.close();const reopened=await openStore(config,true);try{assert.equal((await goalGet(reopened,g.id)).confirmedAt,confirmed);assert.equal((await reopened.get(a.id)).annotation.note,'迁移保留备注');}finally{await reopened.close();}}
 finally{await store.close().catch(()=>{});}
});

import {claimReminder,acknowledgeReminder} from '../server/reminders.mjs';
test('MySQL: 提醒领取互斥、过期恢复与确认',{skip:!enabled},async()=>{const {store}=await testStore('agentdock_test_reminders');try{const s=await store.putDocument('schedule',{title:'合成提醒',start:Date.now()-1000,end:Date.now()+60000,reminderMinutes:0,done:false});const claims=await Promise.all(['desktop','browser'].map(owner=>claimReminder(store,{id:s.id,owner})));assert.equal(claims.filter(c=>c.claimed).length,1);await assert.rejects(acknowledgeReminder(store,{id:s.id,claim:'invalid'}),/过期/);const old=await store.document(s.id,'schedule');await store.putDocument('schedule',{...old,claimUntil:Date.now()-1});const next=await claimReminder(store,{id:s.id,owner:'browser'});assert.equal(next.claimed,true);await acknowledgeReminder(store,{id:s.id,claim:next.token});assert.equal((await claimReminder(store,{id:s.id,owner:'desktop'})).claimed,false);}finally{await store.close();}});
