import {connectionOptions} from '../server/store.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {zstdCompressSync} from 'node:zlib';import {mkdtempSync,writeFileSync,appendFileSync,mkdirSync} from 'node:fs';import path from 'node:path';
import {emptyTask,finalize} from '../server/parsers.mjs';import {consumeExtra,zstdFrames,decodeFrame} from '../server/adapters.mjs';import {readCompressed,workbuddyTaskDirectory} from '../server/collector.mjs';import {protect,publicSettings,validateDatabase,discoverSources} from '../server/config.mjs';import {redact,sealPreview,ModelClient} from '../server/model.mjs';import {period,validateSchedule} from '../server/workspace.mjs';import {createServer} from 'node:http';
const ev={path:'sample.jsonl',line:1};
test('Pi 分支、WorkBuddy 待办与 Harness 完成边界',()=>{const p=emptyTask('pi','initial','pi.jsonl');[{type:'session',id:'pi-native',version:3,cwd:''},{type:'message',id:'a',parentId:null,message:{role:'user',content:'实现分支'}},{type:'message',id:'b',parentId:'a',message:{role:'assistant',content:[{type:'text',text:'方案一'}]}},{type:'message',id:'c',parentId:'a',message:{role:'assistant',content:[{type:'text',text:'方案二'},{type:'thinking',thinking:'秘密推理'}]}}].forEach(r=>consumeExtra(p,r,ev));assert.equal(p.branches.length,2);assert.equal(p.summary,'方案二');assert.equal(p.inferredBranch,'c');assert.ok(!JSON.stringify(p.branches).includes('秘密推理'));
 const w=emptyTask('workbuddy','wb','wb.jsonl');consumeExtra(w,{type:'message',sessionId:'wb',role:'user',content:'修复问题'},ev);consumeExtra(w,{type:'message',sessionId:'wb',role:'assistant',content:'本轮已处理'},ev);assert.equal(w.summary,'本轮已处理');const h=emptyTask('deepseek','h','h.jsonl');consumeExtra(h,{type:'turn/end',data:{reason:'completed'},time:Date.now()},ev);assert.equal(finalize(h).completion,'unconfirmed');assert.equal(h.activity,'responded');consumeExtra(h,{type:'turn/end',data:{reason:{kind:'completed'}},time:Date.now()},ev);assert.equal(h.activity,'responded');consumeExtra(h,{type:'turn/end',data:{reason:{kind:'blocked'}},time:Date.now()},ev);assert.equal(finalize(h).completion,'blocked');});
test('Zstandard 拼接帧、尾帧截断和断点恢复',async()=>{mkdirSync('artifacts/unit',{recursive:true});const dir=mkdtempSync(path.resolve('artifacts/unit/zstd-'));const file=path.join(dir,'session.jsonl.zstd');const a=zstdCompressSync(Buffer.from(JSON.stringify({type:'session',version:0,id:'harness-id',createdAt:Date.now()})+'\n'));const b=zstdCompressSync(Buffer.from(JSON.stringify({type:'assistant/message',time:Date.now(),data:{message:{content:'回复内容'}}})+'\n'));const bytes=Buffer.concat([a,b]);assert.equal(zstdFrames(bytes).frames.length,2);assert.match(decodeFrame(b),/回复内容/);writeFileSync(file,bytes.subarray(0,-3));const first=await readCompressed(file,null);assert.equal(first.unfinished,true);assert.equal(first.line,1);appendFileSync(file,bytes.subarray(-3));const second=await readCompressed(file,{task:first.task,size:first.stats.size,mtime:first.stats.mtimeMs,offset:first.offset,line:first.line});assert.equal(second.task.summary,'回复内容');assert.equal(second.line,2);});
test('凭据脱敏、远程 TLS 默认与周边界',()=>{assert.equal(connectionOptions({host:'db.synthetic.example',tls:true}).ssl.verifyIdentity,true);assert.equal(validateDatabase({host:'db.example',port:3306,user:'test-user',password:'synthetic-pass',database:'test_db'}).tls,true);assert.equal(period('weekly','2026-10-04').date,'2026-09-28');assert.throws(()=>period('daily','2026-02-30'));assert.throws(()=>validateSchedule({title:'无效',start:2,end:1}));const safe=sealPreview({text:'synthetic-key password=123456 sk-test-secret-12345'},['synthetic-key']);assert.ok(!safe.text.includes('synthetic-key'));assert.ok(!safe.text.includes('123456'));assert.equal(safe.fingerprint.length,64);});
test('Windows DPAPI 当前用户凭据往返', {skip:process.platform!=='win32'},()=>{const key='  合成凭据😀 synthetic-secret-for-tests  ';const protectedValue=protect(key);assert.ok(!protectedValue.includes(key));assert.equal(protect(protectedValue,true),key);});
test('DeepSeek 流式脱敏、认证头和不自动重试',async()=>{let body,auth,calls=0;const server=createServer(async(req,res)=>{calls++;auth=req.headers.authorization;let raw='';for await(const c of req)raw+=c;body=JSON.parse(raw);res.writeHead(200,{'Content-Type':'text/event-stream'});res.write('data: '+JSON.stringify({choices:[{delta:{content:'依据 [1]：syn'}}]})+'\n\n');res.write('data: '+JSON.stringify({choices:[{delta:{content:'thetic-api-secret\n下一步验证。'}}],usage:{total_tokens:9}})+'\n\n');res.end('data: [DONE]\n\n');});await new Promise(r=>server.listen(0,'127.0.0.1',r));const key='synthetic-api-secret';const client=new ModelClient({key,base:`http://127.0.0.1:${server.address().port}`});const deltas=[];try{const r=await client.generate({question:'分析',preview:{text:'事实'},onDelta:s=>deltas.push(s)});assert.equal(auth,'Bearer '+key);assert.ok(!JSON.stringify(body.messages).includes(key));assert.ok(!deltas.join('').includes(key));assert.ok(r.text.includes('[凭据已隐藏]'));assert.equal(calls,1);assert.equal(r.usage.total_tokens,9);}finally{server.close();}});
test('DeepSeek 错误、断流与停止都不自动重试',async()=>{let calls=0;let mode='denied';const server=createServer((req,res)=>{calls++;if(mode==='denied'){res.writeHead(401);res.end();}else if(mode==='broken'){res.writeHead(200,{'Content-Type':'text/event-stream'});res.end('data: '+JSON.stringify({choices:[{delta:{content:'未完成'}}]})+'\n\n');}else{res.writeHead(200,{'Content-Type':'text/event-stream'});res.write('data: '+JSON.stringify({choices:[{delta:{content:'开始分析\n'}}]})+'\n\n');const timer=setTimeout(()=>res.end('data: [DONE]\n\n'),2000);res.on('close',()=>clearTimeout(timer));}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const client=new ModelClient({key:'synthetic-test-key',base:`http://127.0.0.1:${server.address().port}`});try{await assert.rejects(client.generate({question:'分析',preview:{text:'事实'}}),/认证失败/);assert.equal(calls,1);mode='broken';await assert.rejects(client.generate({question:'分析',preview:{text:'事实'}}),/中断/);assert.equal(calls,2);mode='slow';const controller=new AbortController();const response=client.generate({question:'分析',preview:{text:'事实'},signal:controller.signal,onDelta:()=>controller.abort()});await assert.rejects(response);assert.equal(calls,3);}finally{server.close();}});

test('WorkBuddy 日志 ID 不能跳出待办目录读取认证文件',()=>{assert.equal(workbuddyTaskDirectory('/synthetic','../../auth'),null);assert.equal(workbuddyTaskDirectory('/synthetic','C:\\private'),null);assert.equal(workbuddyTaskDirectory('/synthetic','session-id'),path.join('/synthetic','tasks','session-id'));});
