import {ChatThread} from './ChatThread';
import {Screens,Pane,Switcher,useSection,useListSize} from '../Screen';
import {Paged} from '../Pagination';
import {useEffect,useRef,useState} from 'react';
import {demoOverview,demoPage} from '../demo';
import type {Task,TaskPage} from '../types';
import {request,saveFile as download} from '../api';
import {api,today,datetime,epoch} from './shared';
import type {Props,Settings,Discovery,Report,Schedule,Preview,Chat,ContextRef} from './shared';
export default function AssistantPage({ demo, overview, refs, setRefs, openTask, notify, onDraft, onSource, onRemember, questionDraft }: Props) {
  const contextSize=useListSize(5,190);const [initialScreen]=useState(refs.length?'preview':'chat');const [,setAssistantScreen]=useSection('助手',initialScreen);const [category,setCategory]=useSection('上下文类型','task');
  const [tasks, setTasks] = useState<Task[]>([]); const [reports, setReports] = useState<Report[]>([]); const [schedules, setSchedules] = useState<Schedule[]>([]); const [chats, setChats] = useState<Chat[]>([]); const [chat, setChat] = useState<Chat>(); const [preview, setPreview] = useState<Preview>(); const [question, setQuestion] = useState(questionDraft||'请分析当前进展、阻塞与下一步，并附来源。'); const [error, setError] = useState(''); const [answer, setAnswer] = useState(''); const [busy, setBusy] = useState(false); const [search, setSearch] = useState(''); const [start, setStart] = useState(new Date(Date.now() + 28800000 - 30 * 86400000).toISOString().slice(0, 10)); const [end, setEnd] = useState(today()); const abort = useRef<AbortController | null>(null);
  const [chatRevision,setChatRevision]=useState(0),[pendingQuestion,setPendingQuestion]=useState('');
  const signature=JSON.stringify([refs,start,end]);const currentSignature=useRef(signature);currentSignature.current=signature;const [previewSignature,setPreviewSignature]=useState('');const answerRefs=useRef<ContextRef[]>([]);
  useEffect(()=>{setPreview(undefined);if(!refs.length)return;const controller=new AbortController();const timer=setTimeout(()=>void makePreview(controller.signal),250);return()=>{clearTimeout(timer);controller.abort();};},[signature,demo]);
  useEffect(() => () => abort.current?.abort(), []);
  useEffect(()=>{const controller=new AbortController();const timer=setTimeout(()=>{if(demo){setTasks(demoPage(search,'','','',1).tasks);return;}void request<TaskPage>(`/api/tasks?q=${encodeURIComponent(search)}`,{signal:controller.signal}).then(t=>setTasks(t.tasks)).catch(e=>{if(!controller.signal.aborted)setError(e.message);});},250);return()=>{clearTimeout(timer);controller.abort();};},[demo,search]);
  useEffect(()=>{if(demo)return;const controller=new AbortController();void Promise.all([request<Report[]>('/api/reports',{signal:controller.signal}),request<Schedule[]>('/api/schedules',{signal:controller.signal}),request<Chat[]>('/api/assistant/chats?headers=true',{signal:controller.signal})]).then(([r,s,c])=>{if(!controller.signal.aborted){setReports(r);setSchedules(s);setChats(c);}}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[demo]);
  const add = (type: ContextRef['type'], id: string) => { setRefs(refs.some(r => r.type === type && r.id === id) ? refs.filter(r => r.type !== type || r.id !== id) : [...refs, { type, id }]); };
  const selected = (type: ContextRef['type'], id: string) => refs.some(r => r.type === type && r.id === id);
  async function makePreview(signal?:AbortSignal) { const key=signature; setError(''); try { if (demo) { setPreviewSignature(key);setPreview({ id: 'demo', text: '独立演示上下文：已接入多工具任务，下一步验证来源和迁移。', characters: 30, estimatedTokens: 15, fingerprint: 'demo', sources: refs.map((r, i) => ({ ...r, number: i + 1, title: '演示对象' })) }); return; } const result=await request<Preview>('/api/assistant/context',{method:'POST',signal,body:JSON.stringify({refs,range:{start:Date.parse(start+'T00:00:00+08:00'),end:Date.parse(end+'T00:00:00+08:00')+86400000}})});if(!signal?.aborted&&currentSignature.current===key){setPreview(result);setPreviewSignature(key);} } catch (e) { if(!signal?.aborted&&currentSignature.current===key)setError((e as Error).message); } }
  async function generate() { if (!preview || previewSignature!==signature || busy) return; answerRefs.current=preview.sources.map(({type,id})=>({type,id}));setAssistantScreen('chat');setPendingQuestion(question);setQuestion('');setBusy(true); setAnswer(''); setError(''); if (demo) { setAnswer('【模拟回答】根据当前示例，建议优先验证来源覆盖，区分来源完成声明与人工确认。[1]'); setBusy(false); return; } const controller = new AbortController(); abort.current = controller; let chatId = chat?.id,accepted=false;
    try { const response = await fetch('/api/assistant/generate', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ previewId: preview.id, fingerprint: preview.fingerprint, question, ...(chatId ? { chatId } : {}) }), signal: controller.signal }); if (!response.ok) throw new Error((await response.json()).error); const reader = response.body!.getReader(); const decoder = new TextDecoder(); let pending = ''; for (;;) { const chunk = await reader.read(); if (chunk.done) break; pending += decoder.decode(chunk.value, { stream: true }); const blocks = pending.split('\n\n'); pending = blocks.pop()!; for (const block of blocks) { const event = block.match(/^event: (.*)$/m)?.[1]; const value = block.match(/^data: (.*)$/m)?.[1]; if (!value) continue; const data = JSON.parse(value); if (event === 'chat'){accepted=true;chatId=data.id;setChat(v=>v?.id===data.id?v:{id:data.id,title:question,messages:[]});} if (event === 'delta') setAnswer(t => t + data.text); if (event === 'error') setError(data.error); } } }
    catch (e) { if(!accepted){setPendingQuestion('');setQuestion(v=>v||question);}setError(controller.signal.aborted ? '已停止生成；已接收片段保留在聊天历史中' : (e as Error).message); } finally { setBusy(false); abort.current = null; if (chatId) { await new Promise(r => setTimeout(r, 200)); try { setChatRevision(v=>v+1);setChats(await api<Chat[]>('/api/assistant/chats?headers=true')); } catch { /* Can reload the saved chat later. */ } } }
  }
  const [goals,setGoals]=useState<{id:string;title:string}[]>([]);useEffect(()=>{if(!demo)void api<{goals:{id:string;title:string}[]}>('/api/goals').then(r=>setGoals(r.goals)).catch(()=>{});},[demo]);
  const [memories,setMemories]=useState<{id:string;title:string}[]>([]),[workflows,setWorkflows]=useState<{id:string;title:string}[]>([]);useEffect(()=>{if(demo){setMemories([{id:'demo-memory',title:'演示：验证完成再标记交付'}]);return;}let active=true;void Promise.all([api<{items:{id:string;title:string}[]}>('/api/memories?status=verified'),api<{items:{id:string;title:string}[]}>('/api/workflows')]).then(([m,w])=>{if(active){setMemories(m.items);setWorkflows(w.items);}}).catch(()=>{});return()=>{active=false;};},[demo]);
  const collections: { type: ContextRef['type']; label: string; items: { id: string; title: string }[] }[] = [{type:'memory',label:'已确认记忆（近期 30 项）',items:memories},{type:'workflow',label:'工作流（近期 30 项）',items:workflows},{type:'goal',label:'工作目标',items:demo?[{id:'demo-goal',title:'演示交付目标'}]:goals},{ type: 'task', label: '会话（搜索后显示前 30 项）', items: tasks }, { type: 'project', label: '项目（默认近 30 天）', items: (overview || (demo ? demoOverview() : null))?.projects.map(p => ({ id: p.id, title: p.name })) || [] }, { type: 'report', label: '日报与周报', items: reports }, { type: 'schedule', label: '日程', items: schedules.map(s => ({ id: s.id!, title: s.title })) }];
  return <><div className="section-heading"><h2>AgentDock 内置助手</h2><span>选取上下文 → 自动预览 → 点击发送</span></div><p className="muted">只发送预览中选中内容；正文需主动选择，密钥及内部推理不会加入。</p>{error&&<div className="error-banner" role="alert">{error}</div>}<Screens id="助手" choices={[{id:'chat',label:'聊天'},{id:'context',label:'选择上下文'},{id:'range',label:'上下文范围'},{id:'preview',label:'发送预览'},{id:'history',label:'聊天历史'},{id:'save',label:'保存建议'}]} initial={initialScreen}>
<Pane id="chat" className="assistant-body source-panel"><div className="assistant-context-bar">已选 {refs.length} 项 · {preview?`${preview.characters} 字符，预览已生成`:'等待选择上下文'}<button className="text-button" onClick={()=>setAssistantScreen('preview')}>查看发送预览 →</button></div><ChatThread chat={chat} revision={chatRevision} pending={pendingQuestion?{question:pendingQuestion,answer}:undefined} busy={busy} demo={demo} onSource={onSource}/><div className="chat-composer"><label className="field-label">你的问题<textarea aria-label="助手问题" rows={2} value={question} onChange={e => setQuestion(e.target.value)} /></label><div className="actions"><button className="primary-button" disabled={!preview || previewSignature!==signature || busy || !question.trim()} onClick={() => void generate()}>确认内容并发送</button>{busy && <button className="outline-button" onClick={() => abort.current?.abort()}>停止生成</button>}</div></div></Pane>
<Pane id="context" className="context-picker source-panel"><label className="field-label">搜索会话<input aria-label="搜索上下文" value={search} onChange={e => setSearch(e.target.value)} /></label><Switcher label="上下文类型" value={category} onChange={setCategory} choices={[...collections.map(c=>({id:c.type,label:c.label})),{id:'selected',label:'已选对象'}]}/>{collections.filter(c=>c.type===category).map(c => <details key={c.type} open><summary>{c.label}</summary><Paged label="上下文对象" size={contextSize}>{c.items.map(t => <div className="context-row" key={t.id}><label className="check-field"><input type="checkbox" checked={selected(c.type, t.id)} onChange={() => add(c.type, t.id)} />{t.title}</label>{c.type === 'task' && selected('task', t.id) && <label className="check-field transcript"><input type="checkbox" checked={refs.find(r => r.id === t.id)?.includeTranscript || false} onChange={e => setRefs(refs.map(r => r.id === t.id ? { ...r, includeTranscript: e.target.checked } : r))} />发送所选日期的用户/助手正文</label>}</div>)}</Paged></details>)}{category==='selected'&&<div className="context-selected">已选 {refs.length} 项<Paged label="已选上下文" size={contextSize}>{refs.map(r=><div key={r.type+r.id}>{collections.find(c=>c.type===r.type)?.items.find(x=>x.id===r.id)?.title||r.id}<button className="text-button" onClick={()=>setRefs(refs.filter(x=>!(x.type===r.type&&x.id===r.id)))}>移除</button></div>)}</Paged></div>}<div className="actions"><button disabled={!refs.length || busy} className="primary-button" onClick={() => setAssistantScreen("preview")}>查看发送预览</button><button className="text-button" onClick={() => setRefs([])}>清空</button></div></Pane><Pane id="range" className="source-panel"><h3>上下文日期范围</h3><div className="actions"><button className="text-button" onClick={()=>{setStart(today());setEnd(today());}}>仅今天</button><button className="text-button" onClick={()=>setRefs(refs.map(r=>({...r,includeTranscript:false})))}>仅保留摘要上下文</button></div><div className="form-grid"><label className="field-label">范围开始<input type="date" value={start} onChange={e => setStart(e.target.value)} /></label><label className="field-label">范围结束<input type="date" value={end} onChange={e => setEnd(e.target.value)} /></label></div><p className="muted">改变范围后会自动刷新预览。默认仅使用摘要，正文需在对象列表中单独勾选。</p></Pane><Pane id="preview" className="source-panel assistant-preview">{preview && <details open><summary>发送预览 · {preview.characters} 字符 · 约 {preview.estimatedTokens} tokens</summary><pre className="context-preview">{preview.text}</pre><Paged label="预览来源">{preview.sources.map(s => <p key={s.number}>[{s.number}] {s.title} <code className="evidence-path">{s.evidence?.path}:{s.evidence?.line}</code></p>)}</Paged></details>}{!preview&&<p className="muted">选择上下文后自动生成预览。</p>}<div className="actions"><button className="primary-button" onClick={()=>setAssistantScreen('chat')}>返回聊天</button><button className="outline-button" disabled={!refs.length||busy} onClick={()=>void makePreview()}>重新生成预览</button></div></Pane>
<Pane id="history" className="source-panel"><h3>聊天历史</h3><button className="text-button" disabled={busy} onClick={() => { setChat(undefined);setPendingQuestion('');setAnswer('');setAssistantScreen('chat'); }}>新聊天</button><Paged label="聊天历史">{chats.map(c => <div className="context-row" key={c.id}><button className="text-button" disabled={busy} onClick={async () => { try{setChat(c);setPendingQuestion('');setAnswer('');setAssistantScreen('chat');}catch(e){setError((e as Error).message);} }}>{c.title}</button><button className="text-button" aria-label={`删除聊天 ${c.title}`} onClick={async () => { await api(`/api/assistant/chats/${c.id}`, {}, 'DELETE'); setChats(v => v.filter(x => x.id !== c.id)); if (chat?.id === c.id) setChat(undefined); }}>删除</button></div>)}</Paged></Pane><Pane id="save" className="source-panel">{answer && <><h3>保存分析建议（需确认）</h3>{onRemember&&<button className="outline-button" disabled={busy} onClick={()=>onRemember({title:"助手分析 · 待核实",text:answer,refs:answerRefs.current})}>分析沉淀为记忆草稿</button>}<select aria-label="保存分析的报告" defaultValue="" onChange={async e => { if (!e.target.value) return; try { if (!demo) await api(`/api/reports/${e.target.value}/analysis`, { chatId: chat?.id }); notify('分析补充已确认保存'); } catch (error) { setError((error as Error).message); } }}><option value="">选择报告，确认保存独立 AI 版本…</option>{reports.map(r => <option key={r.id} value={r.id}>{r.title}</option>)}</select><button className="outline-button" onClick={() => onDraft({title:'AI 分析跟进（待编辑）',note:answer})}>创建日程草稿，编辑后确认</button></>}{!answer&&<p className="muted">生成回答后，可确认保存为记忆、报告补充或日程草稿。</p>}</Pane></Screens></>;
}
