import {stat,readFile} from 'node:fs/promises';import {existsSync} from 'node:fs';import path from 'node:path';import {DatabaseSync} from 'node:sqlite';import {walk} from './collector.mjs';
export async function validateSource(id,root){
 if(!path.isAbsolute(root))throw new Error('请填写绝对数据目录');let info;try{info=await stat(root);}catch{return {ok:false,records:0,files:0,message:'数据目录未找到'};}if(!info.isDirectory())return {ok:false,records:0,files:0,message:'请填写会话数据目录，不能填写程序或日志文件'};
 if(id==='cursor'&&existsSync(path.join(root,'Cursor.exe')))return {ok:false,files:0,records:0,message:'这是 Cursor 安装目录，请使用当前用户 AppData/Roaming/Cursor/User 数据目录'};
 let files=0,records=0,unreadable=0,drafts=0;
 if(id==='cursor'){const candidates=[];const global=path.join(root,'globalStorage','state.vscdb');if(existsSync(global))candidates.push(global);for await(const f of walk(path.join(root,'workspaceStorage'),'.vscdb'))candidates.push(f);const ids=new Set(),draftIds=new Set();for(const file of candidates){let db;try{db=new DatabaseSync(file,{readOnly:true,timeout:150});db.exec('PRAGMA query_only=ON');const tables=db.prepare("SELECT name FROM sqlite_master WHERE type='table'").all().map(r=>r.name);if(!tables.some(t=>['composerHeaders','cursorDiskKV','ItemTable'].includes(t))){unreadable++;continue;}files++;if(tables.includes('composerHeaders'))for(const r of db.prepare('SELECT composerId,value FROM composerHeaders').all()){let h;try{h=JSON.parse(r.value);}catch{unreadable++;continue;}if(h.isDraft){drafts++;draftIds.add(r.composerId);}else ids.add(r.composerId);}if(tables.includes('ItemTable'))for(const r of db.prepare("SELECT value FROM ItemTable WHERE key='composer.composerData'").all()){try{for(const h of JSON.parse(r.value)?.allComposers||[]){if(h.isDraft){drafts++;draftIds.add(h.composerId);}else if(h.composerId)ids.add(h.composerId);}}catch{unreadable++;}}if(tables.includes('cursorDiskKV'))for(const r of db.prepare("SELECT key FROM cursorDiskKV WHERE key LIKE 'composerData:%'").all())ids.add(r.key.slice(13));}catch{unreadable++;}finally{db?.close();}}for(const id of draftIds)ids.delete(id);records=ids.size;
 }else{const sub=id==='codex'?['sessions','archived_sessions']:id==='claude'||id==='workbuddy'?['projects']:['sessions'];for(const dir of sub)for await(const f of walk(path.join(root,dir),'.jsonl')){files++;try{const handle=await (await import('node:fs/promises')).open(f,'r');try{const buffer=Buffer.alloc(65536),r=await handle.read(buffer,0,buffer.length,0);const first=buffer.subarray(0,r.bytesRead).toString('utf8').split('\n').find(x=>x.trim());if(first){const item=JSON.parse(first);if(item&&typeof item==='object')records++;else unreadable++;}}finally{await handle.close();}}catch{unreadable++;}}if(id==='deepseek')for await(const f of walk(path.join(root,'sessions'),'.jsonl.zstd')){files++;records++;}}
 return {ok:files>0,files,records,drafts,unreadable,message:files?`发现 ${files} 份记录文件；${records} 个候选会话，${unreadable} 份暂不可读。完整覆盖以采集结果为准。`:'目录存在，但未发现支持的会话记录；可保存后等待首次记录'};
}
