import {useEffect,useState} from 'react';
import {api} from './workspace/shared';
interface Status {durationMinutes:number;intervalSeconds:number;paused:boolean;deadline:number|null;reason:string}
export function CollectionSettings({demo,notify}:{demo:boolean;notify:(s:string)=>void}) {
  const [status,setStatus]=useState<Status>(),[minutes,setMinutes]=useState(60),[interval,setIntervalSeconds]=useState(60),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{if(demo)return;let active=true;const load=async()=>{try{const s=await api<Status>('/api/collection');if(active)setStatus(s);}catch{}};void load();const timer=setInterval(()=>void load(),15000);return()=>{active=false;clearInterval(timer);};},[demo]);
  useEffect(()=>{if(status){setMinutes(status.durationMinutes);setIntervalSeconds(status.intervalSeconds);}},[status?.durationMinutes,status?.intervalSeconds]);
  async function action(save:boolean){if(demo){notify('演示模式：采集设置不会保存');return;}setBusy(true);setError('');try{const s=save?await api<Status>('/api/collection',{durationMinutes:minutes,intervalSeconds:interval},'PATCH'):await api<{paused:boolean}>('/api/collection/pause',{paused:!status?.paused});if(save)setStatus(s as Status);else setStatus(await api<Status>('/api/collection'));notify(save?'采集设置已保存，时长用于下次启动':'采集状态已更新');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <article className="source-panel collection-settings"><h3>采集与资源控制</h3><p aria-live="polite">{status?.paused?status.reason||'采集已暂停':status?.deadline?`采集将在 ${new Date(status.deadline).toLocaleTimeString('zh-CN')} 自动停止`:'等待连接采集服务'}</p><div className="form-grid"><label className="field-label">每次采集时长（分钟）<input aria-label="每次采集时长" type="number" min="1" max="240" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><label className="field-label">检查间隔（秒）<select aria-label="采集检查间隔" value={interval} onChange={e=>setIntervalSeconds(Number(e.target.value))}>{[15,30,60,120,300].map(n=><option key={n} value={n}>{n} 秒</option>)}</select></label></div><p className="muted">默认每次 1 小时、每 60 秒检查。到期释放监听与采集缓存，重启保持暂停；点击恢复开启新一轮。历史分批读取，暂停后保留断点。到期仅停止采集，已有记录仍可浏览。</p>{error&&<p role="alert">{error}</p>}<div className="actions"><button className="outline-button" disabled={busy} onClick={()=>void action(true)}>保存采集设置</button><button className="primary-button" disabled={busy||(!status&&!demo)} onClick={()=>void action(false)}>{status?.paused?'恢复采集':'暂停采集'}</button></div></article>;
}
