import {useEffect,useState} from 'react';
import {Activity,ArrowRight,Clock3,Layers3,Radio} from 'lucide-react';
import {request} from './api';
import type {Overview} from './types';
import {Screens,Pane} from './Screen';
export default function Home({overview,demo,revision,go,flow,exportToday}:{overview:Overview;demo:boolean;revision:number;go:(view:string,id?:string)=>void;flow:()=>void;exportToday:()=>void}){
 const [next,setNext]=useState<{id:string;title:string;type:string}[]>([]),[dates,setDates]=useState<{id:string;title:string;start:number}[]>([]);
 useEffect(()=>{if(demo){setNext([{id:'demo-goal',title:'确认数据库迁移方案',type:'goals'}]);return;}let active=true;void Promise.all([request<{goals:{id:string;title:string}[]}>('/api/goals?attention=true&pageSize=2'),request<{tasks:{id:string;title:string}[]}>('/api/tasks?attention=true&pageSize=2'),request<{id:string;title:string;start:number;done:boolean}[]>('/api/schedules')]).then(([g,t,s])=>{if(active){setNext([...g.goals.map(n=>({...n,type:'goals'})),...t.tasks.map(n=>({...n,type:'task'}))].slice(0,2));setDates(s.filter(n=>!n.done&&n.start>=Date.now()).sort((a,b)=>a.start-b.start).slice(0,2));}}).catch(()=>{});return()=>{active=false;};},[demo,revision]);
 const tasks=<article className="home-card"><Activity/><h2>跨工具任务流</h2><strong>{overview.recent.toLocaleString()} <small>个近期会话</small></strong><button className="primary-button" onClick={flow}>查看跨工具任务流 <ArrowRight size={15}/></button><button className="text-button" onClick={()=>go('sources')}>查看工具接入与覆盖</button></article>;
 const actions=<article className="home-card"><Radio/><h2>下一步需要处理</h2>{next.length?next.map(n=><button className="home-link" key={n.id} onClick={()=>go(n.type,n.id)}>{n.title}<ArrowRight size={14}/></button>):<p className="muted">没有明确阻塞或主动标记。</p>}<button className="text-button" onClick={()=>go('goals')}>查看全部工作目标 →</button></article>;
 const calendar=<article className="home-card"><Clock3/><h2>近期日程</h2>{dates.length?dates.map(n=><button className="home-link" key={n.id} onClick={()=>go('calendar',n.id)}>{n.title}<small>{new Date(n.start).toLocaleDateString('zh-CN')}</small></button>):<p className="muted">暂未安排日程。</p>}<button className="text-button" onClick={()=>go('calendar')}>打开日历 →</button></article>;
 const assets=<article className="home-card"><Layers3/><h2>记忆与工作流</h2><div className="home-assets">{[['memories','记忆库'],['workflows','工作流'],['assistant','内置助手']].map(([v,label])=><button className="outline-button" key={v} onClick={()=>go(v)}>{label} →</button>)}</div></article>;
 return <section className="home-screen"><div className="section-heading"><h1>工作台</h1><button className="outline-button" onClick={exportToday}>导出今日摘要</button></div><div className="metrics">{[[Activity,'近期活动',overview.recent],[Radio,'待你处理',overview.needsAttention],[Layers3,'今日进展',overview.today]].map(([Icon,label,n])=>{const I=Icon as typeof Activity;return <article className="metric" key={String(label)}><div><span>{String(label)}</span><I size={18}/></div><strong>{Number(n).toLocaleString()}</strong></article>;})}</div><p className="home-brief">今日 {overview.today} 个会话留下进展，{overview.doneToday} 个任务确认完成。</p><div className="home-wide home-grid">{tasks}{actions}{calendar}{assets}</div><div className="home-small"><Screens id="工作台内容" choices={[{id:'overview',label:'总览'},{id:'actions',label:'下一步'}]}><Pane id="overview" className="home-grid">{tasks}{assets}</Pane><Pane id="actions" className="home-grid">{actions}{calendar}</Pane></Screens></div></section>;
}
