import {BrowserRouter} from 'react-router';
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import {AuthGate} from './Auth';
import './styles.css';
import './workbench.css';
import './polish.css';
import './usage.css';
import './studio.css';
import './compact.css';
import './screen.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><AuthGate><App /></AuthGate></BrowserRouter></React.StrictMode>);
