import {Screens,Pane,Steps} from './Screen';
import {useEffect,useState} from 'react';
import {request} from './api';
import {tools} from './UsageHistory';
import {datetime,epoch,useUnsavedChanges} from './workspace/shared';
import {Paged} from './Pagination';
type Entry={id:string;provider:string;model:string;input:number;output:number;timestamp:number;note:string;version:number;refine:boolean;deleted?:boolean};
const blank=()=>({id:crypto.randomUUID(),provider:'codex',model:'',input:0,output:0,timestamp:Date.now()-60000,note:'',version:0,refine:false});
export function ManualUsage({demo,onSaved}:{demo:boolean;onSaved:()=>void}){
  const [entries,setEntries]=useState<Entry[]>([]),[form,setForm]=useState<Entry>(),[error,setError]=useState(''),[busy,setBusy]=useState(false);useUnsavedChanges(Boolean(form));
  async function load(){if(!demo)setEntries(await request<Entry[]>('/api/usage/manual'));}useEffect(()=>{void load().catch(()=>{});},[demo]);
  async function save(remove=false,entry=form){if(!entry)return;setBusy(true);setError('');try{if(demo)throw new Error('演示模式不保存补录');const id=entry.id.replace(/^manual-/,'');await request('/api/usage/manual',{method:remove?'DELETE':'POST',body:JSON.stringify(remove?{id,version:entry.version}:{id,provider:entry.provider,model:entry.model,input:entry.input,output:entry.output,timestamp:entry.timestamp,note:entry.note,version:entry.version,refine:entry.refine})});setForm(undefined);await load();onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <section className="source-panel manual-usage"><h3>精确用量补录 · 输入、输出与时间点</h3><p className="muted">手动录入独立保留依据与修改版本。选择“细化历史余额”可避免与已有补录重复相加；单独追加仅用于未统计的用量。请核对是否已由日志采集。</p><button className="outline-button" onClick={()=>setForm(blank())}>新增精确补录</button>{form&&<form noValidate data-dirty="true" onSubmit={e=>{e.preventDefault();void save();}}><Screens id="精确补录编辑" choices={[{id:"tokens",label:"用量与时间"},{id:"note",label:"依据"}]}><Pane id="tokens"><Steps label="精确用量步骤"><label className="field-label">工具<select value={form.provider} onChange={e=>setForm({...form,provider:e.target.value})}>{Object.entries(tools).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="field-label">模型<input required aria-label="补录模型" value={form.model} onChange={e=>setForm({...form,model:e.target.value})}/></label><label className="field-label">输入 Token<input required aria-label="补录输入 Token" type="number" min="0" step="1" value={form.input} onChange={e=>setForm({...form,input:Number(e.target.value)})}/></label><label className="field-label">输出 Token<input required aria-label="补录输出 Token" type="number" min="0" step="1" value={form.output} onChange={e=>setForm({...form,output:Number(e.target.value)})}/></label><label className="field-label">日期时间（Asia/Shanghai）<input required aria-label="补录日期时间" type="datetime-local" step="1" value={Number.isFinite(form.timestamp)?new Date(form.timestamp+28800000).toISOString().slice(0,19):''} onChange={e=>setForm({...form,timestamp:Date.parse(e.target.value+(e.target.value.length===16?':00':'')+'+08:00')})}/></label><label className="field-label">计入方式<select value={String(form.refine)} onChange={e=>setForm({...form,refine:e.target.value==='true'})}><option value="false">单独追加</option><option value="true">细化历史余额（总量不变）</option></select></label></Steps></Pane><Pane id="note"><label className="field-label">补录依据<textarea required aria-label="精确补录依据" maxLength={4000} value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label></Pane></Screens><div className="actions"><button className="primary-button" disabled={busy}>保存精确补录</button><button type="button" className="outline-button" onClick={()=>setForm(undefined)}>取消</button></div></form>}{error&&<p role="alert">{error}</p>}{!form&&<Paged label="精确补录">{entries.filter(e=>!e.deleted).map(e=><div className="report-fact" key={e.id}><strong>{tools[e.provider]} · {e.model}</strong><p>{new Date(e.timestamp).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})} · 输入 {e.input.toLocaleString()} · 输出 {e.output.toLocaleString()} · 手动录入</p><button className="text-button" disabled={busy} onClick={()=>setForm(e)}>编辑</button><button className="text-button" disabled={busy} onClick={()=>{if(confirm('删除此补录？修订记录仍保留。'))void save(true,e);}}>删除</button></div>)}</Paged>}</section>;
}
