import { useEffect, useState } from 'react';
import { ArrowRight, BookOpen, GitBranch, Sparkles, Check, Clock3, Plus, ArrowDownToLine } from 'lucide-react';
import { api, useUnsavedChanges, type ContextRef } from './workspace/shared';
import { saveFile } from './api';
import type { Overview } from './types';

type Ref = ContextRef & { title?: string };
export interface MemoryDraft { title: string; text: string; refs: Ref[]; projectId?: string }
interface Memory extends MemoryDraft { id: string; category: string; status: string; tags: string[]; version: number; reviewAt: number | null; reviewCount: number; updatedAt: number }
interface Step { title: string; note: string; completedAt: number | null }
interface Run { id: string; title: string; templateId: string; refs: Ref[]; projectId: string; steps: Step[]; status: string; version: number }
interface Template { id: string; title: string; description: string; steps: string[] }
const labels: Record<string,string> = { draft:'待确认', verified:'已确认', archived:'已归档', active:'进行中', completed:'已完成', decision:'决策', pattern:'可复用经验', pitfall:'避坑', preference:'工作偏好' };
const demoTemplates: Template[] = [
  {id:'delivery',title:'跨工具交付',description:'对齐目标、整理方案、验证结果，再沉淀经验。',steps:['对齐目标与依据','整理方案与分工','核对验证与风险','交付复盘与记忆']},
  {id:'unblock',title:'阻塞诊断',description:'从证据出发，记录假设和验证结果。',steps:['收集阻塞证据','提出可验证假设','记录验证结果','沉淀避坑经验']},
  {id:'review',title:'每周复盘',description:'结合报告和记忆安排下一周行动。',steps:['回顾本周事实','对照已有经验','制定下一周行动','更新长期记忆']},
];
let demoMemories: Memory[] = [{id:'demo-memory',title:'验证完成再标记交付',text:'本轮回复结束只代表一次交互结束。交付前应核对测试和来源，再由用户确认。',refs:[],category:'pattern',status:'verified',tags:['交付','验证'],version:1,reviewAt:Date.now()-1,reviewCount:0,updatedAt:Date.now()}];
let demoRuns: Run[] = [];
const emptyMemory = (): Omit<Memory,'id'> & { id?: string } => ({title:'',text:'',refs:[],category:'pattern',status:'draft',tags:[],version:0,reviewAt:null,reviewCount:0,updatedAt:0,projectId:''});
const date = (n: number) => new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'short',day:'numeric'}).format(n);
const refKey = (r: Ref) => r.type+':'+r.id;

export function ProductLoop({demo,revision,go}:{demo:boolean;revision:number;go:(view:string)=>void}) {
  const [counts,setCounts]=useState<{memories:number;due:number;runs:number}>();
  useEffect(()=>{let active=true;if(demo){setCounts({memories:demoMemories.filter(m=>m.status==='verified').length,due:demoMemories.filter(m=>m.status==='verified'&&!!m.reviewAt&&m.reviewAt<=Date.now()).length,runs:demoRuns.filter(r=>r.status==='active').length});return;}void Promise.all([api<{total:number}>('/api/memories?status=verified'),api<{total:number}>('/api/memories?due=true'),api<{total:number}>('/api/workflows?status=active')]).then(([m,d,w])=>{if(active)setCounts({memories:m.total,due:d.total,runs:w.total});}).catch(()=>{if(active)setCounts(undefined);});return()=>{active=false;};},[demo,revision]);
  return <section className="product-loop" aria-label="记忆工作流闭环"><div className="loop-heading"><span className="studio-eyebrow">YOUR WORK, CONNECTED</span><h2>让这一次工作，帮助下一次。</h2><p>记录 → 记忆 → 工作流 → 交互 → 复盘</p></div><div className="loop-cards">
    <button className="loop-card memory-tone" onClick={()=>go('memories')}><BookOpen/><span className="loop-badge">长期积累</span><h3>记忆库</h3><p>{counts?`${counts.memories} 条已确认 · ${counts.due} 条待复查`:'把决策与经验整理成可复用记忆'}</p><span>沉淀工作经验 <ArrowRight size={15}/></span></button>
    <button className="loop-card flow-tone" onClick={()=>go('workflows')}><GitBranch/><span className="loop-badge">逐步推进</span><h3>工作流</h3><p>{counts?`${counts.runs} 个进行中 · 每一步留下结论`:'交付、诊断和复盘的引导式步骤'}</p><span>推进下一步 <ArrowRight size={15}/></span></button>
    <button className="loop-card chat-tone" onClick={()=>go('assistant')}><Sparkles/><span className="loop-badge">上下文交互</span><h3>内置助手</h3><p>选取记忆与工作记录，预览后分析。</p><span>带着依据思考 <ArrowRight size={15}/></span></button>
  </div></section>;
}

interface Props {view:string;demo:boolean;revision:number;overview:Overview|null;refs:ContextRef[];draft?:MemoryDraft;focus?:ContextRef;consumeDraft:()=>void;notify:(s:string)=>void;openSource:(r:ContextRef)=>void;analyze:(refs:ContextRef[],question:string)=>void;remember:(d:MemoryDraft)=>void;schedule:(d:{title:string;note:string})=>void}
export default function Studio({view,demo,revision,overview,refs,draft,focus,consumeDraft,notify,openSource,analyze,remember,schedule}:Props) {
  const isMemory=view==='memories',kind=isMemory?'memories':'workflows';
  const [items,setItems]=useState<(Memory|Run)[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[q,setQ]=useState(''),[status,setStatus]=useState(''),[project,setProject]=useState(''),[due,setDue]=useState(false),[tick,setTick]=useState(0),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState('');
  const [memory,setMemory]=useState<ReturnType<typeof emptyMemory>>(),[baseline,setBaseline]=useState(''),[run,setRun]=useState<Run>(),[note,setNote]=useState(''),[templates,setTemplates]=useState<Template[]>(demoTemplates),[templateId,setTemplateId]=useState('delivery'),[title,setTitle]=useState(''),[creating,setCreating]=useState(false),[selectedRefs,setSelectedRefs]=useState<Ref[]>(refs),[options,setOptions]=useState<Ref[]>([]);
  const dirty=Boolean(memory&&JSON.stringify(memory)!==baseline)||Boolean(note.trim())||Boolean(creating&&(title.trim()||selectedRefs.length));useUnsavedChanges(dirty);
  useEffect(()=>{let active=true;setLoading(true);setError('');if(demo){let records:(Memory|Run)[]=isMemory?demoMemories:demoRuns;records=records.filter(x=>(status?x.status===status:x.status!=='archived')&&(!project||x.projectId===project)&&JSON.stringify(x).includes(q)&&(!due||('reviewAt'in x&&x.status==='verified'&&!!x.reviewAt&&x.reviewAt<=Date.now())));setItems(records.slice((page-1)*30,page*30));setTotal(records.length);setLoading(false);return;}const p=new URLSearchParams({q,status,project,page:String(page),...(due?{due:'true'}:{})});void api<{items:(Memory|Run)[];total:number}>(`/api/${kind}?${p}`).then(r=>{if(active){setItems(r.items);setTotal(r.total);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[kind,demo,q,status,project,due,page,tick,revision]);
  useEffect(()=>{if(demo){setOptions([{type:'memory',id:'demo-memory',title:'演示：验证完成再标记交付'}]);return;}let active=true;void Promise.all([api<{tasks:{id:string;title:string}[]}>('/api/tasks'),api<{items:Memory[]}>('/api/memories?status=verified'),api<{goals:{id:string;title:string}[]}>('/api/goals'),api<{id:string;title:string}[]>('/api/reports'),api<Template[]>('/api/workflows/templates')]).then(([t,m,g,r,templates])=>{if(active){setTemplates(templates);setOptions([...m.items.map(x=>({type:'memory' as const,id:x.id,title:x.title})),...t.tasks.map(x=>({type:'task' as const,id:x.id,title:x.title})),...g.goals.map(x=>({type:'goal' as const,id:x.id,title:x.title})),...r.slice(0,30).map(x=>({type:'report' as const,id:x.id,title:x.title}))]);}}).catch(()=>{});return()=>{active=false;};},[demo,tick]);
  function edit(m:ReturnType<typeof emptyMemory>){setMemory(m);setBaseline(JSON.stringify(m));setRun(undefined);setError('');}
  useEffect(()=>{if(isMemory&&draft){edit({...emptyMemory(),...draft,title:draft.title.slice(0,200),text:draft.text.slice(0,16000)});consumeDraft();}},[draft,isMemory]);
  useEffect(()=>{if(focus&&(focus.type===(isMemory?'memory':'workflow')))void open(focus.id);},[focus?.id,isMemory]);
  async function open(id:string){if(dirty&&!confirm('修改尚未保存，是否放弃？'))return;try{const item=demo?(isMemory?demoMemories:demoRuns).find(x=>x.id===id):await api<Memory|Run>(`/api/${kind}/${encodeURIComponent(id)}`);if(!item)throw new Error('对象不存在');if(isMemory)edit(item as Memory);else{setRun(item as Run);setNote('');setCreating(false);}}catch(e){setError((e as Error).message);}}
  async function mutate(action:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await action();setTick(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function saveMemory(){if(!memory)return;await mutate(async()=>{const payload={...(memory.id?{id:memory.id,version:memory.version}:{}),title:memory.title,text:memory.text,category:memory.category,status:memory.status,tags:memory.tags,projectId:memory.projectId||'',refs:memory.refs.map(({type,id})=>({type,id}))};if(!payload.title.trim()||!payload.text.trim())throw new Error('请填写标题和记忆内容');let saved:Memory;if(demo){saved={...memory,id:memory.id||crypto.randomUUID(),version:memory.version+1,updatedAt:Date.now()} as Memory;demoMemories=[saved,...demoMemories.filter(x=>x.id!==saved.id)];}else saved=await api<Memory>('/api/memories',payload);edit(saved);notify(demo?'记忆已保存到独立演示模式':'记忆已保存；原始会话保持只读');});}
  const chosen=templates.find(t=>t.id===templateId),current=run?.steps.findIndex(s=>!s.completedAt)??-1;
  function picker(values:Ref[],change:(r:Ref[])=>void){const all=[...values,...options.filter(o=>!values.some(r=>refKey(r)===refKey(o)))].filter(o=>!(memory?.id===o.id&&o.type==='memory'));return <details className="studio-picker"><summary>关联依据 · 已选 {values.length} 项（每类近期记录；其他会话可从详情加入）</summary>{all.map(o=><label className="check-field" key={refKey(o)}><input type="checkbox" checked={values.some(r=>refKey(r)===refKey(o))} onChange={()=>change(values.some(r=>refKey(r)===refKey(o))?values.filter(r=>refKey(r)!==refKey(o)):[...values,o])}/><span>{o.title||o.id} <small>{o.type}</small></span></label>)}</details>;}
  return <section className="studio-page" data-dirty={dirty}><div className="studio-intro"><span className="studio-eyebrow">{isMemory?'MEMORY LIBRARY':'GUIDED WORKFLOWS'}</span><h2>{isMemory?'经验有出处，下次有帮助。':'把一次工作，推进成一次交付。'}</h2><p>{isMemory?'保存决策、偏好和避坑经验。草稿需人工确认，7 天后复查；同步不会覆盖你的编辑。':'选取目标与记忆，逐步记录结论。助手提供建议，每一步由你确认，不执行 IDE 命令。'}</p></div>
    {demo&&<div className="demo-banner">独立演示模式 · 记忆和工作流仅保存在当前页面进程，不连接数据库或模型。</div>}
    {error&&<div className="error-banner" role="alert">{error}</div>}
    <div className="studio-toolbar"><input aria-label="搜索记忆或工作流" placeholder="搜索内容、标签与来源…" value={q} onChange={e=>{setQ(e.target.value);setPage(1);}}/><select aria-label="记忆或工作流状态" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">未归档</option>{(isMemory?['draft','verified','archived']:['active','completed','archived']).map(s=><option key={s} value={s}>{labels[s]}</option>)}</select><select aria-label="记忆或工作流项目" value={project} onChange={e=>{setProject(e.target.value);setPage(1);}}><option value="">全部项目</option>{overview?.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>{isMemory&&<label className="check-field"><input type="checkbox" checked={due} onChange={e=>{setDue(e.target.checked);setStatus('');setPage(1);}}/>待复查</label>}<button className="primary-button" onClick={()=>{if(dirty&&!confirm('修改尚未保存，是否放弃？'))return;if(isMemory)edit(emptyMemory());else{setCreating(true);setRun(undefined);setTitle('');setNote('');setSelectedRefs(refs.slice(0,20));}}}><Plus size={15}/>{isMemory?'新建记忆':'启动工作流'}</button></div>
    <div className="studio-layout"><aside className="studio-list source-panel"><div className="section-heading"><h3>{isMemory?'记忆索引':'工作流记录'}</h3><span>{total} 项</span></div>{loading&&<p role="status">正在读取…</p>}{items.map(item=><button key={item.id} className={`studio-item ${item.id===(isMemory?memory?.id:run?.id)?'selected':''}`} onClick={()=>void open(item.id)}><span className="studio-item-top"><strong>{item.title}</strong><small>{labels[item.status]}</small></span>{'text'in item?<><p>{item.text.slice(0,100)}</p><span className="studio-tags">{labels[item.category]} · {item.tags.join(' / ')||'无标签'}{item.reviewAt&&` · ${date(item.reviewAt)} 复查`}</span></>:<><p>{item.steps.filter(s=>s.completedAt).length} / {item.steps.length} 步已确认</p><span className="studio-tags">{item.steps.find(s=>!s.completedAt)?.title||'全部步骤已确认'}</span></>}</button>)}{!loading&&!items.length&&<div className="studio-empty"><BookOpen/><h3>{isMemory?'让工作留下经验':'从一个小流程开始'}</h3><p>{q||status||project||due?'调整筛选，查看其他记录。':'从会话详情沉淀记忆，或点击上方按钮开始。'}</p></div>}<div className="pagination"><button className="text-button" disabled={page===1} onClick={()=>setPage(page-1)}>上一页</button><span>{page} / {Math.max(1,Math.ceil(total/30))}</span><button className="text-button" disabled={page*30>=total} onClick={()=>setPage(page+1)}>下一页</button></div></aside>
      <article className="source-panel studio-editor">
        {isMemory&&memory?<><div className="section-heading"><h3>{memory.id?'编辑记忆':'记忆草稿'}</h3><span>来源陈述需核实</span></div><label className="field-label">记忆标题<input aria-label="记忆标题" maxLength={200} value={memory.title} onChange={e=>setMemory({...memory,title:e.target.value})}/></label><div className="form-grid"><label className="field-label">类别<select value={memory.category} onChange={e=>setMemory({...memory,category:e.target.value})}>{['decision','pattern','pitfall','preference'].map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label><label className="field-label">确认状态<select aria-label="记忆确认状态" value={memory.status} onChange={e=>setMemory({...memory,status:e.target.value})}>{['draft','verified','archived'].map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label></div><label className="field-label">关联项目<select value={memory.projectId||''} onChange={e=>setMemory({...memory,projectId:e.target.value})}><option value="">通用经验</option>{overview?.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="field-label">记忆内容<textarea aria-label="记忆内容" rows={9} maxLength={16000} value={memory.text} onChange={e=>setMemory({...memory,text:e.target.value})}/></label><label className="field-label">标签（逗号分隔，最多 8 个）<input aria-label="记忆标签" value={memory.tags.join(',')} onChange={e=>setMemory({...memory,tags:e.target.value.split(/[,，]/).slice(0,8)})}/></label>{picker(memory.refs,r=>setMemory({...memory,refs:r}))}<div className="studio-evidence">{memory.refs.map(r=><button className="text-button" key={refKey(r)} onClick={()=>openSource(r)}>依据：{r.title||r.id} ↗</button>)}</div><div className="actions"><button className="primary-button" disabled={busy} onClick={()=>void saveMemory()}><Check size={15}/>保存记忆</button>{memory.id&&<><button className="outline-button" disabled={dirty} onClick={()=>analyze([{type:'memory',id:memory.id!}],'请结合这条记忆分析适用条件、可能过时的部分与下一次实践建议，引用依据。')}><Sparkles size={15}/>带入助手</button><button className="outline-button" disabled={dirty} onClick={()=>{saveFile(`# ${memory.title}\n\n状态：${labels[memory.status]}\n\n${memory.text}\n\n## 来源\n\n${memory.refs.map(r=>`- ${r.title||r.id} (${r.type}:${r.id})`).join('\n')}`,'agentdock-memory.md');}}><ArrowDownToLine size={15}/>导出</button></>}</div>{memory.id&&memory.status==='verified'&&<div className="studio-review"><Clock3 size={15}/><span>已复查 {memory.reviewCount} 次 · 下次 {memory.reviewAt?date(memory.reviewAt):'待安排'}</span>{[1,7,30].map(days=><button className="text-button" key={days} disabled={busy||dirty} onClick={()=>void mutate(async()=>{if(demo){const m={...memory,version:memory.version+1,reviewCount:memory.reviewCount+1,reviewAt:Date.now()+days*86400000} as Memory;demoMemories=demoMemories.map(x=>x.id===m.id?m:x);edit(m);}else edit(await api<Memory>(`/api/memories/${memory.id}/review`,{version:memory.version,days}));notify(`已复查，${days} 天后再次复查`);})}>复查后 {days} 天</button>)}</div>}</>
        :!isMemory&&creating?<><h3>选择适合这次工作的流程</h3><div className="template-grid">{templates.map(t=><button key={t.id} className={`template-card ${templateId===t.id?'selected':''}`} onClick={()=>setTemplateId(t.id)}><GitBranch size={18}/><strong>{t.title}</strong><p>{t.description}</p><small>{t.steps.length} 个步骤</small></button>)}</div><label className="field-label">工作流名称<input aria-label="工作流名称" value={title} maxLength={200} placeholder={chosen?.title} onChange={e=>setTitle(e.target.value)}/></label><label className="field-label">工作流项目<select value={project} onChange={e=>setProject(e.target.value)}><option value="">不限定项目</option>{overview?.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{picker(selectedRefs,setSelectedRefs)}<button className="primary-button" disabled={busy} onClick={()=>void mutate(async()=>{let r:Run;if(demo){r={id:crypto.randomUUID(),title:title||chosen!.title,templateId,refs:selectedRefs,projectId:project,status:'active',version:1,steps:chosen!.steps.map(title=>({title,note:'',completedAt:null}))};demoRuns=[r,...demoRuns];}else r=await api<Run>('/api/workflows',{title:title||chosen?.title,templateId,projectId:project,refs:selectedRefs.map(({type,id})=>({type,id}))});setRun(r);setCreating(false);notify('工作流已启动');})}>确认启动 <ArrowRight size={15}/></button></>
        :!isMemory&&run?<><div className="section-heading"><h3>{run.title}</h3><span>{labels[run.status]}</span></div><div className="workflow-steps">{run.steps.map((s,i)=><section className={`workflow-step ${i===current?'current':''}`} key={i}><div className="step-number">{s.completedAt?<Check size={16}/>:String(i+1).padStart(2,'0')}</div><div><h4>{s.title}</h4><small>{s.completedAt?`用户确认 · ${date(s.completedAt)}`:i===current?'当前步骤':'等待前一步确认'}</small>{s.note&&<p className="preserve">{s.note}</p>}</div></section>)}</div>{run.status==='active'&&current>=0&&<><label className="field-label">本步结论 / 验证结果<textarea aria-label="工作流步骤结论" rows={5} maxLength={16000} value={note} onChange={e=>setNote(e.target.value)} placeholder="记录实际做了什么、验证依据和待处理问题…"/></label><div className="actions"><button className="outline-button" onClick={()=>analyze([{type:'workflow',id:run.id},...run.refs.map(({type,id})=>({type,id}))],`当前工作流「${run.title}」第 ${current+1} 步：${run.steps[current].title}。请结合所选记忆与来源提供可验证的下一步建议，说明证据不足之处。`)}><Sparkles size={15}/>用助手分析本步</button><button className="primary-button" disabled={busy||!note.trim()} onClick={()=>void mutate(async()=>{let saved:Run;if(demo){saved={...run,version:run.version+1,steps:run.steps.map((s,i)=>i===current?{...s,note,completedAt:Date.now()}:s)};if(saved.steps.every(s=>s.completedAt))saved.status='completed';demoRuns=demoRuns.map(x=>x.id===saved.id?saved:x);}else saved=await api<Run>(`/api/workflows/${run.id}/step`,{version:run.version,step:current,note});setRun(saved);setNote('');notify('本步已确认，结论已保存');})}>确认本步 <ArrowRight size={15}/></button></div></>}<div className="studio-evidence">{run.refs.map(r=><button className="text-button" key={refKey(r)} onClick={()=>openSource(r)}>依据：{r.title||r.id} ↗</button>)}</div><div className="actions"><button className="outline-button" disabled={!run.steps.some(s=>s.note)} onClick={()=>remember({title:`${run.title} · 复盘`,text:run.steps.filter(s=>s.note).map(s=>`${s.title}\n${s.note}`).join('\n\n'),refs:[{type:'workflow',id:run.id,title:run.title}],projectId:run.projectId})}><BookOpen size={15}/>结论沉淀为记忆</button><button className="outline-button" onClick={()=>schedule({title:`跟进：${run.title}`,note:`工作流：${run.id}\n${run.steps.find(s=>!s.completedAt)?.title||'复查交付结论'}`})}>创建跟进日程草稿</button>{run.status==='active'&&<button className="text-button" disabled={busy} onClick={()=>{if(!confirm('归档此工作流？未完成步骤将保留。'))return;void mutate(async()=>{const r=demo?{...run,status:'archived',version:run.version+1}:await api<Run>(`/api/workflows/${run.id}/step`,{version:run.version,archive:true});if(demo)demoRuns=demoRuns.map(x=>x.id===r.id?r:x);setRun(r);setNote('');});}}>归档</button>}<button className="text-button" onClick={()=>void open(run.id)}>重新载入</button></div></>
        :<div className="studio-empty"><Sparkles size={30}/><h3>{isMemory?'把一次结论变成长期资产':'让经验参与每一个步骤'}</h3><p>{isMemory?'从左侧选择记忆，或从任意会话详情创建草稿。':'工作流会保留关联来源、每步结论和确认记录。完成后可沉淀记忆，并创建回访日程。'}</p></div>}
      </article>
    </div>
  </section>;
}
