import {Screens,Pane,Steps} from './Screen';
import {Paged} from './Pagination';
import {useState} from 'react';
import {request} from './api';
import {today,useUnsavedChanges} from './workspace/shared';
export type Allocation={provider:string;model:string;weight:number;since?:string;total?:number};
export type History={config:null|{distribution?:string;enabled:boolean;start:string;end:string;note:string;allocations:Allocation[];anchorAt:number;targetAtAnchor:number;versions:unknown[]};availableTotal:number;recovered:number;total:number;periodTotal:number;days:{day:number;total:number}[];allocations:(Allocation&{total:number})[];periodAllocations:(Allocation&{total:number})[];projectExcluded:boolean};
export const tools:Record<string,string>={codex:'Codex',claude:'Claude Code',cursor:'Cursor',pi:'Pi CLI',deepseek:'DeepSeek Harness',workbuddy:'WorkBuddy',agentdock:'AgentDock 助手',unknown:'未区分工具'};
export function HistoryEditor({history,onSaved}:{history?:History;onSaved:()=>void}){
  const [open,setOpen]=useState(false),[distribution,setDistribution]=useState('flexible'),[mode,setMode]=useState('amount'),[amount,setAmount]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[note,setNote]=useState(''),[rows,setRows]=useState<Allocation[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  useUnsavedChanges(open);
  function edit(){const c=history?.config;setMode(c?'amount':'target');setDistribution(c?.distribution|| (c?'weekdays':'flexible'));setAmount(c?String((history?.availableTotal||0)/1e8):'');setStart(c?.start||`${Number(today().slice(0,4))-1}${today().slice(4)}`);setEnd(c?.end||new Date(Date.parse(today()+'T00:00:00Z')-86400000).toISOString().slice(0,10));setNote(c?.note||'');setRows(c?.allocations||[{provider:'unknown',model:'未区分模型',weight:10000}]);setError('');setOpen(true);}
  async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{if(!/^\d+(\.\d{1,8})?$/.test(amount))throw new Error('请输入有效亿 Token 数，最多八位小数');const [integer,fraction='']=amount.split('.');const count=BigInt(integer)*100000000n+BigInt(fraction.padEnd(8,'0'));if(count>BigInt(Number.MAX_SAFE_INTEGER))throw new Error('Token 超过安全范围');await request('/api/usage/history',{method:'POST',body:JSON.stringify({distribution,mode,tokens:Number(count),start,end,note,allocations:rows})});setOpen(false);onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function disable(){if(!confirm('停用手动补录？日志实测不受影响，历史版本仍保留。'))return;setBusy(true);try{await request('/api/usage/history',{method:'DELETE'});onSaved();setOpen(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <section className="source-panel history-panel"><div className="section-heading"><div><span className="auth-kicker">HISTORY BASELINE</span><h3>历史用量补录</h3></div><button className="outline-button" onClick={edit} disabled={busy}>管理历史补录</button></div>
    <p className="muted">{history?.config?.enabled?`补录余额 ${(history.availableTotal/1e8).toFixed(2)} 亿 · 已用恢复日志替换 ${(history.recovered/1e8).toFixed(2)} 亿。`:'未补录；累计数字仅来自日志。'} 比例补录的日期由规则分配，不生成请求、输入输出或账单。</p>
    {history?.projectExcluded&&<p className="warning">手动补录未归属项目，当前项目筛选仅显示实测。</p>}
    {open&&<form noValidate data-dirty="true" onSubmit={e=>void save(e)}><Screens id="历史补录编辑" choices={[{id:'range',label:'数量与范围'},{id:'allocation',label:'模型分配'},{id:'note',label:'依据'}]}><Pane id="range"><Steps label="历史范围步骤"><label className="field-label">补录方式<select value={mode} onChange={e=>setMode(e.target.value)}><option value="target">校准累计基准</option><option value="amount">替换历史补录余额</option></select></label><label className="field-label">{mode==='target'?'累计基准（亿 Token）':'历史余额（亿 Token）'}<input required aria-label="历史 Token 数量" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="field-label">历史开始<input required type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="field-label">历史结束<input required type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></Steps><p className="muted">校准只在保存时执行：基准减去当前实测得到补录余额，之后新用量继续累加。再次保存会替换补录；不会重复追加。</p>
</Pane><Pane id="allocation">      <Paged size={1} label="补录分配">{rows.map((r,i)=><div className="history-allocation" key={i}><label>工具<select aria-label={`历史工具 ${i+1}`} value={r.provider} onChange={e=>setRows(rows.map((x,j)=>j===i?{...x,provider:e.target.value}:x))}>{Object.entries(tools).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>模型 / 回忆标签<input required value={r.model} onChange={e=>setRows(rows.map((x,j)=>j===i?{...x,model:e.target.value}:x))}/></label><label>比例 %<input required type="number" min="0.01" max="100" step="0.01" value={r.weight/100} onChange={e=>setRows(rows.map((x,j)=>j===i?{...x,weight:Math.round(Number(e.target.value)*100)}:x))}/></label><label>最早分配日期<input type="date" value={r.since||''} min={start} max={end} onChange={e=>setRows(rows.map((x,j)=>j===i?{...x,since:e.target.value||undefined}:x))}/></label><button type="button" className="text-button" onClick={()=>setRows(rows.filter((_,j)=>j!==i))} disabled={rows.length===1}>移除</button></div>)}</Paged>
      <button type="button" className="text-button" onClick={()=>setRows([...rows,{provider:'unknown',model:'',weight:100}])} disabled={rows.length>=40}>添加分配</button><span className="muted">合计 {rows.reduce((s,r)=>s+r.weight,0)/100}% · 须为 100%</span></Pane><Pane id="note"><Steps label="补录依据步骤"><label className="field-label">日期分布<select aria-label="历史分布方式" value={distribution} onChange={e=>setDistribution(e.target.value)}><option value="flexible">弹性分摊（含少量周末）</option><option value="weekdays">原工作日分摊</option></select></label><label className="field-label">补录依据与说明<textarea required maxLength={4000} value={note} onChange={e=>setNote(e.target.value)}/></label></Steps><p className="muted">弹性分摊按固定规则产生不同深浅，周末较少；旧补录保留原工作日规则，保存后才更改。两种都只是估算，不代表真实活动日期。模型标签可记录你的回忆，不等同官方型号确认。</p></Pane></Screens>{error&&<p role="alert" className="error-banner">{error}</p>}<div className="button-row"><button className="primary-button" disabled={busy}>保存历史补录</button><button type="button" className="outline-button" disabled={busy} onClick={()=>{if(confirm('放弃本次编辑？'))setOpen(false);}}>取消</button>{history?.config?.enabled&&<button type="button" className="text-button" disabled={busy} onClick={()=>void disable()}>停用补录</button>}</div>
      {!!history?.config?.versions.length&&<p className="muted">已保留 {history.config.versions.length} 个修订版本。最近校准：{new Date(history.config.anchorAt).toLocaleString('zh-CN')}。</p>}
    </form>}
  </section>;
}
