import {lazy,Suspense,useEffect,useRef,useState} from 'react';
import {api} from './workspace/shared';
import type {Props,Health,Schedule,Discovery} from './workspace/shared';
import {saveFile as download} from './api';
export {api,today} from './workspace/shared';
export type {ContextRef} from './workspace/shared';
const SettingsPage=lazy(()=>import('./workspace/SettingsPage'));
const ReportsPage=lazy(()=>import('./workspace/ReportsPage'));
const CalendarPage=lazy(()=>import('./workspace/CalendarPage'));
const AssistantPage=lazy(()=>import('./workspace/AssistantPage'));
export function ConnectionNotice({ demo, go }: { demo: boolean; go: () => void }) {
  const delivered = useRef(new Set<string>()); const [health, setHealth] = useState<Health>(); const [reminders, setReminders] = useState<Schedule[]>([]);
  useEffect(() => { if (demo) return; let active = true; const poll = async () => { try { const data = await api<{ database: Health }>('/api/health'); if (!active) return; setHealth(data.database); if (data.database.connected) { const list = await api<Schedule[]>('/api/reminders'); if (active) { setReminders(list); for (const s of list) if(s.id && !delivered.current.has(s.id) && typeof Notification !== 'undefined' && Notification.permission === 'granted' && !window.agentdock && localStorage.getItem('agentdock-notifications') === 'true') { const claim=await api<{claimed:boolean;token?:string}>(`/api/reminders/${s.id}/claim`,{owner:'browser'});if(claim.claimed){new Notification('AgentDock 日程提醒',{body:s.title,tag:s.id});delivered.current.add(s.id);await api(`/api/reminders/${s.id}/ack`,{claim:claim.token});} } } } } catch { /* SSE and the main page also expose connection failures. */ } }; void poll(); const timer = setInterval(() => void poll(), 15000); return () => { active = false; clearInterval(timer); }; }, [demo]);
  return <>{!demo && health && !health.connected && <div className="error-banner">{health.message} · 采集暂停<button onClick={go}>配置数据库</button></div>}{!demo&&health&&(health as Health&{paused?:boolean}).paused&&<p className='import-banner'>采集已暂停，可从桌面托盘恢复。</p>}{!demo&&health&&(health as Health&{reportIssue?:string}).reportIssue&&<p role='alert' className='error-banner'>报告更新失败<button onClick={()=>void api('/api/reports/refresh',{}).then(()=>setHealth({...health,reportIssue:''} as Health)).catch(()=>{})}>重试报告更新</button></p>}{!demo && reminders.map(s => <div className="import-banner" key={s.id}>日程提醒：{s.title}<button onClick={() => { void api(`/api/reminders/${s.id}/ack`, {}).then(() => setReminders(r => r.filter(x => x.id !== s.id))); }}>已处理</button></div>)}</>;
}
export function Workspace(props: Props) {
  return <section className="workspace-page"><Suspense fallback={<p>加载页面…</p>}>{props.demo && <div className="explanation">独立演示数据 · 数据库和模型不会被调用</div>}{props.view === 'settings' ? <SettingsPage {...props} /> : props.view === 'reports' ? <ReportsPage {...props} /> : props.view === 'calendar' ? <CalendarPage {...props} /> : <AssistantPage {...props} />}</Suspense></section>;
}
export function SourceControls({ demo, notify }: { demo: boolean; notify: (s: string) => void }) {
  const [sources, setSources] = useState<Discovery[]>([]); const [error, setError] = useState(''); const [validation,setValidation]=useState<Record<string,string>>({}); const [busy, setBusy] = useState('');
  useEffect(() => { if (!demo) void api<Discovery[]>('/api/sources/discover').then(setSources).catch(e => setError(e.message)); }, [demo]);
  return demo ? null : <details className="source-panel path-settings"><summary>来源路径、发现依据与停用设置</summary>{error && <p role="alert">{error}</p>}{sources.map((s, i) => <div key={s.id} className="source-config"><h3>{s.name}</h3><p>{s.discoveredBy} · {s.exists ? '目录存在' : '目录未找到'} · 程序入口：{s.executable || 'PATH 中未发现'}</p><label className="field-label">数据目录<input aria-label={`${s.name} 数据目录`} value={s.root} onChange={e => setSources(v => v.map((x, j) => j === i ? { ...x, root: e.target.value } : x))} /></label>{window.agentdock&&<button onClick={async()=>{try{const root=await window.agentdock!.chooseSource(s.id);if(root)setSources(v=>v.map((x,j)=>j===i?{...x,root}:x));}catch(e){setError((e as Error).message);}}}>选择数据目录</button>}<label className="check-field"><input type="checkbox" checked={s.enabled} onChange={e => setSources(v => v.map((x, j) => j === i ? { ...x, enabled: e.target.checked } : x))} />启用采集</label><p>{validation[s.id]}</p><button className="outline-button" disabled={Boolean(busy)} onClick={async()=>{try{const r=await api<{message:string}>(`/api/sources/${s.id}/validate`,{root:s.root});setValidation(v=>({...v,[s.id]:r.message}));}catch(e){setError((e as Error).message);}}}>验证记录覆盖</button><button className="outline-button" disabled={Boolean(busy)} onClick={async () => { setBusy(s.id); try { setSources(await api<Discovery[]>(`/api/sources/${s.id}`, { root: s.root, enabled: s.enabled }, 'PATCH')); const r=await api<{message:string}>(`/api/sources/${s.id}/validate`,{root:s.root});setValidation(v=>({...v,[s.id]:r.message}));notify('来源设置已保存，请查看验证结果'); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } }}>验证并保存路径</button></div>)}<button className="outline-button" onClick={async()=>{const r=await api('/api/diagnostics');download(JSON.stringify(r,null,2),'agentdock-diagnostics.json');}}>导出脱敏诊断</button><button className="primary-button" onClick={() => void api('/api/sources/scan', {}).then(() => notify('扫描已启动')).catch(e => setError(e.message))}>扫描已知目录</button></details>;
}
